/*
Veritrance API

Veritrance API 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
)


// AccountApiService AccountApi service
type AccountApiService service

type ApiPaynowV2AddAccountRequest struct {
	ctx context.Context
	ApiService *AccountApiService
	params *string
	authHash *string
}

func (r ApiPaynowV2AddAccountRequest) Params(params string) ApiPaynowV2AddAccountRequest {
	r.params = &params
	return r
}

func (r ApiPaynowV2AddAccountRequest) AuthHash(authHash string) ApiPaynowV2AddAccountRequest {
	r.authHash = &authHash
	return r
}

func (r ApiPaynowV2AddAccountRequest) Execute() (*AccountResponse, *http.Response, error) {
	return r.ApiService.PaynowV2AddAccountExecute(r)
}

/*
PaynowV2AddAccount 会員情報を追加します。

・会員 ID を登録します。
・会員 ID の登録と同時に、カード情報および継続課金情報を紐付けることが可能です。
  継続課金情報を設定する際は、カード情報の同時設定が必要です。
  カード情報を指定した場合、有効性確認が行われます。
・会員 ID の登録と同時に、カード情報のみを紐付けることが可能です。


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPaynowV2AddAccountRequest
*/
func (a *AccountApiService) PaynowV2AddAccount(ctx context.Context) ApiPaynowV2AddAccountRequest {
	return ApiPaynowV2AddAccountRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return AccountResponse
func (a *AccountApiService) PaynowV2AddAccountExecute(r ApiPaynowV2AddAccountRequest) (*AccountResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AccountResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountApiService.PaynowV2AddAccount")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/paynow/v2/Add/account"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.params == nil {
		return localVarReturnValue, nil, reportError("params is required and must be specified")
	}
	if r.authHash == nil {
		return localVarReturnValue, nil, reportError("authHash is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarFormParams.Add("params", parameterToString(*r.params, ""))
	localVarFormParams.Add("authHash", parameterToString(*r.authHash, ""))
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPaynowV2DeleteAccountRequest struct {
	ctx context.Context
	ApiService *AccountApiService
	params *string
	authHash *string
}

func (r ApiPaynowV2DeleteAccountRequest) Params(params string) ApiPaynowV2DeleteAccountRequest {
	r.params = &params
	return r
}

func (r ApiPaynowV2DeleteAccountRequest) AuthHash(authHash string) ApiPaynowV2DeleteAccountRequest {
	r.authHash = &authHash
	return r
}

func (r ApiPaynowV2DeleteAccountRequest) Execute() (*PayNowIdResponse, *http.Response, error) {
	return r.ApiService.PaynowV2DeleteAccountExecute(r)
}

/*
PaynowV2DeleteAccount 会員 ID の会員情報を、指定された「退会年月日」に削除します。

・会員 ID の会員情報を、指定された「退会年月日」に削除します。


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPaynowV2DeleteAccountRequest
*/
func (a *AccountApiService) PaynowV2DeleteAccount(ctx context.Context) ApiPaynowV2DeleteAccountRequest {
	return ApiPaynowV2DeleteAccountRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return PayNowIdResponse
func (a *AccountApiService) PaynowV2DeleteAccountExecute(r ApiPaynowV2DeleteAccountRequest) (*PayNowIdResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PayNowIdResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountApiService.PaynowV2DeleteAccount")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/paynow/v2/Delete/account"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.params == nil {
		return localVarReturnValue, nil, reportError("params is required and must be specified")
	}
	if r.authHash == nil {
		return localVarReturnValue, nil, reportError("authHash is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarFormParams.Add("params", parameterToString(*r.params, ""))
	localVarFormParams.Add("authHash", parameterToString(*r.authHash, ""))
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPaynowV2UpdateAccountRequest struct {
	ctx context.Context
	ApiService *AccountApiService
	params *string
	authHash *string
}

func (r ApiPaynowV2UpdateAccountRequest) Params(params string) ApiPaynowV2UpdateAccountRequest {
	r.params = &params
	return r
}

func (r ApiPaynowV2UpdateAccountRequest) AuthHash(authHash string) ApiPaynowV2UpdateAccountRequest {
	r.authHash = &authHash
	return r
}

func (r ApiPaynowV2UpdateAccountRequest) Execute() (*PayNowIdResponse, *http.Response, error) {
	return r.ApiService.PaynowV2UpdateAccountExecute(r)
}

/*
PaynowV2UpdateAccount 会員 ID の「入会年月日」を更新します。

・会員 ID の「入会年月日」を更新します。


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPaynowV2UpdateAccountRequest
*/
func (a *AccountApiService) PaynowV2UpdateAccount(ctx context.Context) ApiPaynowV2UpdateAccountRequest {
	return ApiPaynowV2UpdateAccountRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return PayNowIdResponse
func (a *AccountApiService) PaynowV2UpdateAccountExecute(r ApiPaynowV2UpdateAccountRequest) (*PayNowIdResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PayNowIdResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountApiService.PaynowV2UpdateAccount")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/paynow/v2/Update/account"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.params == nil {
		return localVarReturnValue, nil, reportError("params is required and must be specified")
	}
	if r.authHash == nil {
		return localVarReturnValue, nil, reportError("authHash is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarFormParams.Add("params", parameterToString(*r.params, ""))
	localVarFormParams.Add("authHash", parameterToString(*r.authHash, ""))
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
