/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardCancelRequestParams struct for CardCancelRequestParams
type CardCancelRequestParams struct {
	TxnVersion string `json:"txnVersion"`
	DummyRequest string `json:"dummyRequest"`
	MerchantCcid string `json:"merchantCcid"`
	OrderId string `json:"orderId"`
	Amount string `json:"amount"`
}

// NewCardCancelRequestParams instantiates a new CardCancelRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardCancelRequestParams(txnVersion string, dummyRequest string, merchantCcid string, orderId string, amount string) *CardCancelRequestParams {
	this := CardCancelRequestParams{}
	this.TxnVersion = txnVersion
	this.DummyRequest = dummyRequest
	this.MerchantCcid = merchantCcid
	this.OrderId = orderId
	this.Amount = amount
	return &this
}

// NewCardCancelRequestParamsWithDefaults instantiates a new CardCancelRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardCancelRequestParamsWithDefaults() *CardCancelRequestParams {
	this := CardCancelRequestParams{}
	return &this
}

// GetTxnVersion returns the TxnVersion field value
func (o *CardCancelRequestParams) GetTxnVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxnVersion
}

// GetTxnVersionOk returns a tuple with the TxnVersion field value
// and a boolean to check if the value has been set.
func (o *CardCancelRequestParams) GetTxnVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxnVersion, true
}

// SetTxnVersion sets field value
func (o *CardCancelRequestParams) SetTxnVersion(v string) {
	o.TxnVersion = v
}

// GetDummyRequest returns the DummyRequest field value
func (o *CardCancelRequestParams) GetDummyRequest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DummyRequest
}

// GetDummyRequestOk returns a tuple with the DummyRequest field value
// and a boolean to check if the value has been set.
func (o *CardCancelRequestParams) GetDummyRequestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DummyRequest, true
}

// SetDummyRequest sets field value
func (o *CardCancelRequestParams) SetDummyRequest(v string) {
	o.DummyRequest = v
}

// GetMerchantCcid returns the MerchantCcid field value
func (o *CardCancelRequestParams) GetMerchantCcid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantCcid
}

// GetMerchantCcidOk returns a tuple with the MerchantCcid field value
// and a boolean to check if the value has been set.
func (o *CardCancelRequestParams) GetMerchantCcidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantCcid, true
}

// SetMerchantCcid sets field value
func (o *CardCancelRequestParams) SetMerchantCcid(v string) {
	o.MerchantCcid = v
}

// GetOrderId returns the OrderId field value
func (o *CardCancelRequestParams) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *CardCancelRequestParams) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *CardCancelRequestParams) SetOrderId(v string) {
	o.OrderId = v
}

// GetAmount returns the Amount field value
func (o *CardCancelRequestParams) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CardCancelRequestParams) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CardCancelRequestParams) SetAmount(v string) {
	o.Amount = v
}

func (o CardCancelRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["txnVersion"] = o.TxnVersion
	}
	if true {
		toSerialize["dummyRequest"] = o.DummyRequest
	}
	if true {
		toSerialize["merchantCcid"] = o.MerchantCcid
	}
	if true {
		toSerialize["orderId"] = o.OrderId
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableCardCancelRequestParams struct {
	value *CardCancelRequestParams
	isSet bool
}

func (v NullableCardCancelRequestParams) Get() *CardCancelRequestParams {
	return v.value
}

func (v *NullableCardCancelRequestParams) Set(val *CardCancelRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableCardCancelRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableCardCancelRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardCancelRequestParams(val *CardCancelRequestParams) *NullableCardCancelRequestParams {
	return &NullableCardCancelRequestParams{value: val, isSet: true}
}

func (v NullableCardCancelRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardCancelRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


