/*
Veritrance API

Veritrance API 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardCaptureRequest struct for CardCaptureRequest
type CardCaptureRequest struct {
	OrderId string `json:"orderId"`
	Amount string `json:"amount"`
}

// NewCardCaptureRequest instantiates a new CardCaptureRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardCaptureRequest(orderId string, amount string) *CardCaptureRequest {
	this := CardCaptureRequest{}
	this.OrderId = orderId
	this.Amount = amount
	return &this
}

// NewCardCaptureRequestWithDefaults instantiates a new CardCaptureRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardCaptureRequestWithDefaults() *CardCaptureRequest {
	this := CardCaptureRequest{}
	return &this
}

// GetOrderId returns the OrderId field value
func (o *CardCaptureRequest) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequest) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *CardCaptureRequest) SetOrderId(v string) {
	o.OrderId = v
}

// GetAmount returns the Amount field value
func (o *CardCaptureRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CardCaptureRequest) SetAmount(v string) {
	o.Amount = v
}

func (o CardCaptureRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["orderId"] = o.OrderId
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableCardCaptureRequest struct {
	value *CardCaptureRequest
	isSet bool
}

func (v NullableCardCaptureRequest) Get() *CardCaptureRequest {
	return v.value
}

func (v *NullableCardCaptureRequest) Set(val *CardCaptureRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardCaptureRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardCaptureRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardCaptureRequest(val *CardCaptureRequest) *NullableCardCaptureRequest {
	return &NullableCardCaptureRequest{value: val, isSet: true}
}

func (v NullableCardCaptureRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardCaptureRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


