/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoAddRequest struct for CardInfoAddRequest
type CardInfoAddRequest struct {
	Params CardInfoAddRequestParams `json:"params"`
	AuthHash string `json:"authHash"`
}

// NewCardInfoAddRequest instantiates a new CardInfoAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoAddRequest(params CardInfoAddRequestParams, authHash string) *CardInfoAddRequest {
	this := CardInfoAddRequest{}
	this.Params = params
	this.AuthHash = authHash
	return &this
}

// NewCardInfoAddRequestWithDefaults instantiates a new CardInfoAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoAddRequestWithDefaults() *CardInfoAddRequest {
	this := CardInfoAddRequest{}
	return &this
}

// GetParams returns the Params field value
func (o *CardInfoAddRequest) GetParams() CardInfoAddRequestParams {
	if o == nil {
		var ret CardInfoAddRequestParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequest) GetParamsOk() (*CardInfoAddRequestParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *CardInfoAddRequest) SetParams(v CardInfoAddRequestParams) {
	o.Params = v
}

// GetAuthHash returns the AuthHash field value
func (o *CardInfoAddRequest) GetAuthHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthHash
}

// GetAuthHashOk returns a tuple with the AuthHash field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequest) GetAuthHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthHash, true
}

// SetAuthHash sets field value
func (o *CardInfoAddRequest) SetAuthHash(v string) {
	o.AuthHash = v
}

func (o CardInfoAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["params"] = o.Params
	}
	if true {
		toSerialize["authHash"] = o.AuthHash
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoAddRequest struct {
	value *CardInfoAddRequest
	isSet bool
}

func (v NullableCardInfoAddRequest) Get() *CardInfoAddRequest {
	return v.value
}

func (v *NullableCardInfoAddRequest) Set(val *CardInfoAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoAddRequest(val *CardInfoAddRequest) *NullableCardInfoAddRequest {
	return &NullableCardInfoAddRequest{value: val, isSet: true}
}

func (v NullableCardInfoAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


