/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam struct for CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam
type CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam struct {
	AccountId string `json:"accountId"`
	CardParam CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParamCardParam `json:"cardParam"`
}

// NewCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam instantiates a new CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam(accountId string, cardParam CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParamCardParam) *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam {
	this := CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam{}
	this.AccountId = accountId
	this.CardParam = cardParam
	return &this
}

// NewCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParamWithDefaults instantiates a new CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParamWithDefaults() *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam {
	this := CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) SetAccountId(v string) {
	o.AccountId = v
}

// GetCardParam returns the CardParam field value
func (o *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) GetCardParam() CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	if o == nil {
		var ret CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParamCardParam
		return ret
	}

	return o.CardParam
}

// GetCardParamOk returns a tuple with the CardParam field value
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) GetCardParamOk() (*CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParamCardParam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardParam, true
}

// SetCardParam sets field value
func (o *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) SetCardParam(v CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParamCardParam) {
	o.CardParam = v
}

func (o CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if true {
		toSerialize["cardParam"] = o.CardParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam struct {
	value *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam
	isSet bool
}

func (v NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) Get() *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam {
	return v.value
}

func (v *NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) Set(val *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam(val *CardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) *NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam {
	return &NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam{value: val, isSet: true}
}

func (v NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoUpdateRequestParamsAllOfPayNowIdParamAccountParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


