/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountResponsePayNowIdResponse struct for AccountResponsePayNowIdResponse
type AccountResponsePayNowIdResponse struct {
	// 会員管理処理を一意に識別する番号
	ProcessId string `json:"processId"`
	// 会員管理処理要求の実行結果
	Status string `json:"status"`
	// 会員管理処理要求の実行結果メッセージ
	Message string `json:"message"`
	Account *AccountV1 `json:"account,omitempty"`
}

// NewAccountResponsePayNowIdResponse instantiates a new AccountResponsePayNowIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResponsePayNowIdResponse(processId string, status string, message string) *AccountResponsePayNowIdResponse {
	this := AccountResponsePayNowIdResponse{}
	this.ProcessId = processId
	this.Status = status
	this.Message = message
	return &this
}

// NewAccountResponsePayNowIdResponseWithDefaults instantiates a new AccountResponsePayNowIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResponsePayNowIdResponseWithDefaults() *AccountResponsePayNowIdResponse {
	this := AccountResponsePayNowIdResponse{}
	return &this
}

// GetProcessId returns the ProcessId field value
func (o *AccountResponsePayNowIdResponse) GetProcessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessId
}

// GetProcessIdOk returns a tuple with the ProcessId field value
// and a boolean to check if the value has been set.
func (o *AccountResponsePayNowIdResponse) GetProcessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessId, true
}

// SetProcessId sets field value
func (o *AccountResponsePayNowIdResponse) SetProcessId(v string) {
	o.ProcessId = v
}

// GetStatus returns the Status field value
func (o *AccountResponsePayNowIdResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AccountResponsePayNowIdResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AccountResponsePayNowIdResponse) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *AccountResponsePayNowIdResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AccountResponsePayNowIdResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AccountResponsePayNowIdResponse) SetMessage(v string) {
	o.Message = v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *AccountResponsePayNowIdResponse) GetAccount() AccountV1 {
	if o == nil || o.Account == nil {
		var ret AccountV1
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponsePayNowIdResponse) GetAccountOk() (*AccountV1, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *AccountResponsePayNowIdResponse) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given AccountV1 and assigns it to the Account field.
func (o *AccountResponsePayNowIdResponse) SetAccount(v AccountV1) {
	o.Account = &v
}

func (o AccountResponsePayNowIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["processId"] = o.ProcessId
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["message"] = o.Message
	}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	return json.Marshal(toSerialize)
}

type NullableAccountResponsePayNowIdResponse struct {
	value *AccountResponsePayNowIdResponse
	isSet bool
}

func (v NullableAccountResponsePayNowIdResponse) Get() *AccountResponsePayNowIdResponse {
	return v.value
}

func (v *NullableAccountResponsePayNowIdResponse) Set(val *AccountResponsePayNowIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResponsePayNowIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResponsePayNowIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResponsePayNowIdResponse(val *AccountResponsePayNowIdResponse) *NullableAccountResponsePayNowIdResponse {
	return &NullableAccountResponsePayNowIdResponse{value: val, isSet: true}
}

func (v NullableAccountResponsePayNowIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResponsePayNowIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


