/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountAddRequestAllOf struct for AccountAddRequestAllOf
type AccountAddRequestAllOf struct {
	AccountId *string `json:"accountId,omitempty"`
	CardNumber *string `json:"cardNumber,omitempty"`
	CardExpire *string `json:"cardExpire,omitempty"`
	SecurityCode *string `json:"securityCode,omitempty"`
}

// NewAccountAddRequestAllOf instantiates a new AccountAddRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountAddRequestAllOf() *AccountAddRequestAllOf {
	this := AccountAddRequestAllOf{}
	return &this
}

// NewAccountAddRequestAllOfWithDefaults instantiates a new AccountAddRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountAddRequestAllOfWithDefaults() *AccountAddRequestAllOf {
	this := AccountAddRequestAllOf{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *AccountAddRequestAllOf) GetAccountId() string {
	if o == nil || o.AccountId == nil {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAddRequestAllOf) GetAccountIdOk() (*string, bool) {
	if o == nil || o.AccountId == nil {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *AccountAddRequestAllOf) HasAccountId() bool {
	if o != nil && o.AccountId != nil {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *AccountAddRequestAllOf) SetAccountId(v string) {
	o.AccountId = &v
}

// GetCardNumber returns the CardNumber field value if set, zero value otherwise.
func (o *AccountAddRequestAllOf) GetCardNumber() string {
	if o == nil || o.CardNumber == nil {
		var ret string
		return ret
	}
	return *o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAddRequestAllOf) GetCardNumberOk() (*string, bool) {
	if o == nil || o.CardNumber == nil {
		return nil, false
	}
	return o.CardNumber, true
}

// HasCardNumber returns a boolean if a field has been set.
func (o *AccountAddRequestAllOf) HasCardNumber() bool {
	if o != nil && o.CardNumber != nil {
		return true
	}

	return false
}

// SetCardNumber gets a reference to the given string and assigns it to the CardNumber field.
func (o *AccountAddRequestAllOf) SetCardNumber(v string) {
	o.CardNumber = &v
}

// GetCardExpire returns the CardExpire field value if set, zero value otherwise.
func (o *AccountAddRequestAllOf) GetCardExpire() string {
	if o == nil || o.CardExpire == nil {
		var ret string
		return ret
	}
	return *o.CardExpire
}

// GetCardExpireOk returns a tuple with the CardExpire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAddRequestAllOf) GetCardExpireOk() (*string, bool) {
	if o == nil || o.CardExpire == nil {
		return nil, false
	}
	return o.CardExpire, true
}

// HasCardExpire returns a boolean if a field has been set.
func (o *AccountAddRequestAllOf) HasCardExpire() bool {
	if o != nil && o.CardExpire != nil {
		return true
	}

	return false
}

// SetCardExpire gets a reference to the given string and assigns it to the CardExpire field.
func (o *AccountAddRequestAllOf) SetCardExpire(v string) {
	o.CardExpire = &v
}

// GetSecurityCode returns the SecurityCode field value if set, zero value otherwise.
func (o *AccountAddRequestAllOf) GetSecurityCode() string {
	if o == nil || o.SecurityCode == nil {
		var ret string
		return ret
	}
	return *o.SecurityCode
}

// GetSecurityCodeOk returns a tuple with the SecurityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAddRequestAllOf) GetSecurityCodeOk() (*string, bool) {
	if o == nil || o.SecurityCode == nil {
		return nil, false
	}
	return o.SecurityCode, true
}

// HasSecurityCode returns a boolean if a field has been set.
func (o *AccountAddRequestAllOf) HasSecurityCode() bool {
	if o != nil && o.SecurityCode != nil {
		return true
	}

	return false
}

// SetSecurityCode gets a reference to the given string and assigns it to the SecurityCode field.
func (o *AccountAddRequestAllOf) SetSecurityCode(v string) {
	o.SecurityCode = &v
}

func (o AccountAddRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountId != nil {
		toSerialize["accountId"] = o.AccountId
	}
	if o.CardNumber != nil {
		toSerialize["cardNumber"] = o.CardNumber
	}
	if o.CardExpire != nil {
		toSerialize["cardExpire"] = o.CardExpire
	}
	if o.SecurityCode != nil {
		toSerialize["securityCode"] = o.SecurityCode
	}
	return json.Marshal(toSerialize)
}

type NullableAccountAddRequestAllOf struct {
	value *AccountAddRequestAllOf
	isSet bool
}

func (v NullableAccountAddRequestAllOf) Get() *AccountAddRequestAllOf {
	return v.value
}

func (v *NullableAccountAddRequestAllOf) Set(val *AccountAddRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountAddRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountAddRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountAddRequestAllOf(val *AccountAddRequestAllOf) *NullableAccountAddRequestAllOf {
	return &NullableAccountAddRequestAllOf{value: val, isSet: true}
}

func (v NullableAccountAddRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountAddRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


