/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoAddRequestAllOf struct for CardInfoAddRequestAllOf
type CardInfoAddRequestAllOf struct {
	PayNowIdParam CardInfoAddRequestAllOfPayNowIdParam `json:"payNowIdParam"`
}

// NewCardInfoAddRequestAllOf instantiates a new CardInfoAddRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoAddRequestAllOf(payNowIdParam CardInfoAddRequestAllOfPayNowIdParam) *CardInfoAddRequestAllOf {
	this := CardInfoAddRequestAllOf{}
	this.PayNowIdParam = payNowIdParam
	return &this
}

// NewCardInfoAddRequestAllOfWithDefaults instantiates a new CardInfoAddRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoAddRequestAllOfWithDefaults() *CardInfoAddRequestAllOf {
	this := CardInfoAddRequestAllOf{}
	return &this
}

// GetPayNowIdParam returns the PayNowIdParam field value
func (o *CardInfoAddRequestAllOf) GetPayNowIdParam() CardInfoAddRequestAllOfPayNowIdParam {
	if o == nil {
		var ret CardInfoAddRequestAllOfPayNowIdParam
		return ret
	}

	return o.PayNowIdParam
}

// GetPayNowIdParamOk returns a tuple with the PayNowIdParam field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequestAllOf) GetPayNowIdParamOk() (*CardInfoAddRequestAllOfPayNowIdParam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PayNowIdParam, true
}

// SetPayNowIdParam sets field value
func (o *CardInfoAddRequestAllOf) SetPayNowIdParam(v CardInfoAddRequestAllOfPayNowIdParam) {
	o.PayNowIdParam = v
}

func (o CardInfoAddRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["payNowIdParam"] = o.PayNowIdParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoAddRequestAllOf struct {
	value *CardInfoAddRequestAllOf
	isSet bool
}

func (v NullableCardInfoAddRequestAllOf) Get() *CardInfoAddRequestAllOf {
	return v.value
}

func (v *NullableCardInfoAddRequestAllOf) Set(val *CardInfoAddRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoAddRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoAddRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoAddRequestAllOf(val *CardInfoAddRequestAllOf) *NullableCardInfoAddRequestAllOf {
	return &NullableCardInfoAddRequestAllOf{value: val, isSet: true}
}

func (v NullableCardInfoAddRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoAddRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


