/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountAddRequest struct for AccountAddRequest
type AccountAddRequest struct {
	Params AccountAddRequestParams `json:"params"`
	AuthHash string `json:"authHash"`
}

// NewAccountAddRequest instantiates a new AccountAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountAddRequest(params AccountAddRequestParams, authHash string) *AccountAddRequest {
	this := AccountAddRequest{}
	this.Params = params
	this.AuthHash = authHash
	return &this
}

// NewAccountAddRequestWithDefaults instantiates a new AccountAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountAddRequestWithDefaults() *AccountAddRequest {
	this := AccountAddRequest{}
	return &this
}

// GetParams returns the Params field value
func (o *AccountAddRequest) GetParams() AccountAddRequestParams {
	if o == nil {
		var ret AccountAddRequestParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *AccountAddRequest) GetParamsOk() (*AccountAddRequestParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *AccountAddRequest) SetParams(v AccountAddRequestParams) {
	o.Params = v
}

// GetAuthHash returns the AuthHash field value
func (o *AccountAddRequest) GetAuthHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthHash
}

// GetAuthHashOk returns a tuple with the AuthHash field value
// and a boolean to check if the value has been set.
func (o *AccountAddRequest) GetAuthHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthHash, true
}

// SetAuthHash sets field value
func (o *AccountAddRequest) SetAuthHash(v string) {
	o.AuthHash = v
}

func (o AccountAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["params"] = o.Params
	}
	if true {
		toSerialize["authHash"] = o.AuthHash
	}
	return json.Marshal(toSerialize)
}

type NullableAccountAddRequest struct {
	value *AccountAddRequest
	isSet bool
}

func (v NullableAccountAddRequest) Get() *AccountAddRequest {
	return v.value
}

func (v *NullableAccountAddRequest) Set(val *AccountAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountAddRequest(val *AccountAddRequest) *NullableAccountAddRequest {
	return &NullableAccountAddRequest{value: val, isSet: true}
}

func (v NullableAccountAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


