/*
Veritrance API

Veritrance API 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountAddResponsePayNowIdResponseAllOf struct for AccountAddResponsePayNowIdResponseAllOf
type AccountAddResponsePayNowIdResponseAllOf struct {
	Account *AccountV2 `json:"account,omitempty"`
}

// NewAccountAddResponsePayNowIdResponseAllOf instantiates a new AccountAddResponsePayNowIdResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountAddResponsePayNowIdResponseAllOf() *AccountAddResponsePayNowIdResponseAllOf {
	this := AccountAddResponsePayNowIdResponseAllOf{}
	return &this
}

// NewAccountAddResponsePayNowIdResponseAllOfWithDefaults instantiates a new AccountAddResponsePayNowIdResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountAddResponsePayNowIdResponseAllOfWithDefaults() *AccountAddResponsePayNowIdResponseAllOf {
	this := AccountAddResponsePayNowIdResponseAllOf{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *AccountAddResponsePayNowIdResponseAllOf) GetAccount() AccountV2 {
	if o == nil || o.Account == nil {
		var ret AccountV2
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAddResponsePayNowIdResponseAllOf) GetAccountOk() (*AccountV2, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *AccountAddResponsePayNowIdResponseAllOf) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given AccountV2 and assigns it to the Account field.
func (o *AccountAddResponsePayNowIdResponseAllOf) SetAccount(v AccountV2) {
	o.Account = &v
}

func (o AccountAddResponsePayNowIdResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	return json.Marshal(toSerialize)
}

type NullableAccountAddResponsePayNowIdResponseAllOf struct {
	value *AccountAddResponsePayNowIdResponseAllOf
	isSet bool
}

func (v NullableAccountAddResponsePayNowIdResponseAllOf) Get() *AccountAddResponsePayNowIdResponseAllOf {
	return v.value
}

func (v *NullableAccountAddResponsePayNowIdResponseAllOf) Set(val *AccountAddResponsePayNowIdResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountAddResponsePayNowIdResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountAddResponsePayNowIdResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountAddResponsePayNowIdResponseAllOf(val *AccountAddResponsePayNowIdResponseAllOf) *NullableAccountAddResponsePayNowIdResponseAllOf {
	return &NullableAccountAddResponsePayNowIdResponseAllOf{value: val, isSet: true}
}

func (v NullableAccountAddResponsePayNowIdResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountAddResponsePayNowIdResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


