/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam struct for CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam
type CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam struct {
	Token string `json:"token"`
}

// NewCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam instantiates a new CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam(token string) *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	this := CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam{}
	this.Token = token
	return &this
}

// NewCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParamWithDefaults instantiates a new CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParamWithDefaults() *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	this := CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam{}
	return &this
}

// GetToken returns the Token field value
func (o *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) SetToken(v string) {
	o.Token = v
}

func (o CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam struct {
	value *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam
	isSet bool
}

func (v NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) Get() *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	return v.value
}

func (v *NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) Set(val *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam(val *CardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) *NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	return &NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam{value: val, isSet: true}
}

func (v NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoAddRequestParamsAllOfPayNowIdParamAccountParamCardParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


