/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountDeleteRequestAllOf struct for AccountDeleteRequestAllOf
type AccountDeleteRequestAllOf struct {
	AccountId *string `json:"accountId,omitempty"`
}

// NewAccountDeleteRequestAllOf instantiates a new AccountDeleteRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountDeleteRequestAllOf() *AccountDeleteRequestAllOf {
	this := AccountDeleteRequestAllOf{}
	return &this
}

// NewAccountDeleteRequestAllOfWithDefaults instantiates a new AccountDeleteRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountDeleteRequestAllOfWithDefaults() *AccountDeleteRequestAllOf {
	this := AccountDeleteRequestAllOf{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *AccountDeleteRequestAllOf) GetAccountId() string {
	if o == nil || o.AccountId == nil {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountDeleteRequestAllOf) GetAccountIdOk() (*string, bool) {
	if o == nil || o.AccountId == nil {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *AccountDeleteRequestAllOf) HasAccountId() bool {
	if o != nil && o.AccountId != nil {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *AccountDeleteRequestAllOf) SetAccountId(v string) {
	o.AccountId = &v
}

func (o AccountDeleteRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountId != nil {
		toSerialize["accountId"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableAccountDeleteRequestAllOf struct {
	value *AccountDeleteRequestAllOf
	isSet bool
}

func (v NullableAccountDeleteRequestAllOf) Get() *AccountDeleteRequestAllOf {
	return v.value
}

func (v *NullableAccountDeleteRequestAllOf) Set(val *AccountDeleteRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountDeleteRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountDeleteRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountDeleteRequestAllOf(val *AccountDeleteRequestAllOf) *NullableAccountDeleteRequestAllOf {
	return &NullableAccountDeleteRequestAllOf{value: val, isSet: true}
}

func (v NullableAccountDeleteRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountDeleteRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


