/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoDeleteRequest struct for CardInfoDeleteRequest
type CardInfoDeleteRequest struct {
	TxnVersion string `json:"txnVersion"`
	DummyRequest string `json:"dummyRequest"`
	MerchantCcid string `json:"merchantCcid"`
	AccountId string `json:"accountId"`
	CardId *string `json:"cardId,omitempty"`
}

// NewCardInfoDeleteRequest instantiates a new CardInfoDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoDeleteRequest(txnVersion string, dummyRequest string, merchantCcid string, accountId string) *CardInfoDeleteRequest {
	this := CardInfoDeleteRequest{}
	this.TxnVersion = txnVersion
	this.DummyRequest = dummyRequest
	this.MerchantCcid = merchantCcid
	this.AccountId = accountId
	return &this
}

// NewCardInfoDeleteRequestWithDefaults instantiates a new CardInfoDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoDeleteRequestWithDefaults() *CardInfoDeleteRequest {
	this := CardInfoDeleteRequest{}
	return &this
}

// GetTxnVersion returns the TxnVersion field value
func (o *CardInfoDeleteRequest) GetTxnVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxnVersion
}

// GetTxnVersionOk returns a tuple with the TxnVersion field value
// and a boolean to check if the value has been set.
func (o *CardInfoDeleteRequest) GetTxnVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxnVersion, true
}

// SetTxnVersion sets field value
func (o *CardInfoDeleteRequest) SetTxnVersion(v string) {
	o.TxnVersion = v
}

// GetDummyRequest returns the DummyRequest field value
func (o *CardInfoDeleteRequest) GetDummyRequest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DummyRequest
}

// GetDummyRequestOk returns a tuple with the DummyRequest field value
// and a boolean to check if the value has been set.
func (o *CardInfoDeleteRequest) GetDummyRequestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DummyRequest, true
}

// SetDummyRequest sets field value
func (o *CardInfoDeleteRequest) SetDummyRequest(v string) {
	o.DummyRequest = v
}

// GetMerchantCcid returns the MerchantCcid field value
func (o *CardInfoDeleteRequest) GetMerchantCcid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantCcid
}

// GetMerchantCcidOk returns a tuple with the MerchantCcid field value
// and a boolean to check if the value has been set.
func (o *CardInfoDeleteRequest) GetMerchantCcidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantCcid, true
}

// SetMerchantCcid sets field value
func (o *CardInfoDeleteRequest) SetMerchantCcid(v string) {
	o.MerchantCcid = v
}

// GetAccountId returns the AccountId field value
func (o *CardInfoDeleteRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CardInfoDeleteRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CardInfoDeleteRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetCardId returns the CardId field value if set, zero value otherwise.
func (o *CardInfoDeleteRequest) GetCardId() string {
	if o == nil || o.CardId == nil {
		var ret string
		return ret
	}
	return *o.CardId
}

// GetCardIdOk returns a tuple with the CardId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardInfoDeleteRequest) GetCardIdOk() (*string, bool) {
	if o == nil || o.CardId == nil {
		return nil, false
	}
	return o.CardId, true
}

// HasCardId returns a boolean if a field has been set.
func (o *CardInfoDeleteRequest) HasCardId() bool {
	if o != nil && o.CardId != nil {
		return true
	}

	return false
}

// SetCardId gets a reference to the given string and assigns it to the CardId field.
func (o *CardInfoDeleteRequest) SetCardId(v string) {
	o.CardId = &v
}

func (o CardInfoDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["txnVersion"] = o.TxnVersion
	}
	if true {
		toSerialize["dummyRequest"] = o.DummyRequest
	}
	if true {
		toSerialize["merchantCcid"] = o.MerchantCcid
	}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if o.CardId != nil {
		toSerialize["cardId"] = o.CardId
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoDeleteRequest struct {
	value *CardInfoDeleteRequest
	isSet bool
}

func (v NullableCardInfoDeleteRequest) Get() *CardInfoDeleteRequest {
	return v.value
}

func (v *NullableCardInfoDeleteRequest) Set(val *CardInfoDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoDeleteRequest(val *CardInfoDeleteRequest) *NullableCardInfoDeleteRequest {
	return &NullableCardInfoDeleteRequest{value: val, isSet: true}
}

func (v NullableCardInfoDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


