/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam struct for CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam
type CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam struct {
	CardId string `json:"cardId"`
}

// NewCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam instantiates a new CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam(cardId string) *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	this := CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam{}
	this.CardId = cardId
	return &this
}

// NewCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParamWithDefaults instantiates a new CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParamWithDefaults() *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	this := CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam{}
	return &this
}

// GetCardId returns the CardId field value
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) GetCardId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardId
}

// GetCardIdOk returns a tuple with the CardId field value
// and a boolean to check if the value has been set.
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) GetCardIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardId, true
}

// SetCardId sets field value
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) SetCardId(v string) {
	o.CardId = v
}

func (o CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cardId"] = o.CardId
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam struct {
	value *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam
	isSet bool
}

func (v NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) Get() *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	return v.value
}

func (v *NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) Set(val *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam(val *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) *NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	return &NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam{value: val, isSet: true}
}

func (v NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


