/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam struct for CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam
type CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam struct {
	Token string `json:"token"`
}

// NewCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam instantiates a new CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam(token string) *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam {
	this := CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam{}
	this.Token = token
	return &this
}

// NewCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParamWithDefaults instantiates a new CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParamWithDefaults() *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam {
	this := CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam{}
	return &this
}

// GetToken returns the Token field value
func (o *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) SetToken(v string) {
	o.Token = v
}

func (o CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam struct {
	value *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam
	isSet bool
}

func (v NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) Get() *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam {
	return v.value
}

func (v *NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) Set(val *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam(val *CardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) *NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam {
	return &NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam{value: val, isSet: true}
}

func (v NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoAddRequestAllOfPayNowIdParamAccountParamCardParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


