/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardAuthorizeRequestAccountParam struct for CardAuthorizeRequestAccountParam
type CardAuthorizeRequestAccountParam struct {
	AccountId string `json:"accountId"`
	CardParam CardAuthorizeRequestCardParam `json:"cardParam"`
}

// NewCardAuthorizeRequestAccountParam instantiates a new CardAuthorizeRequestAccountParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardAuthorizeRequestAccountParam(accountId string, cardParam CardAuthorizeRequestCardParam) *CardAuthorizeRequestAccountParam {
	this := CardAuthorizeRequestAccountParam{}
	this.AccountId = accountId
	this.CardParam = cardParam
	return &this
}

// NewCardAuthorizeRequestAccountParamWithDefaults instantiates a new CardAuthorizeRequestAccountParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardAuthorizeRequestAccountParamWithDefaults() *CardAuthorizeRequestAccountParam {
	this := CardAuthorizeRequestAccountParam{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CardAuthorizeRequestAccountParam) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CardAuthorizeRequestAccountParam) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CardAuthorizeRequestAccountParam) SetAccountId(v string) {
	o.AccountId = v
}

// GetCardParam returns the CardParam field value
func (o *CardAuthorizeRequestAccountParam) GetCardParam() CardAuthorizeRequestCardParam {
	if o == nil {
		var ret CardAuthorizeRequestCardParam
		return ret
	}

	return o.CardParam
}

// GetCardParamOk returns a tuple with the CardParam field value
// and a boolean to check if the value has been set.
func (o *CardAuthorizeRequestAccountParam) GetCardParamOk() (*CardAuthorizeRequestCardParam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardParam, true
}

// SetCardParam sets field value
func (o *CardAuthorizeRequestAccountParam) SetCardParam(v CardAuthorizeRequestCardParam) {
	o.CardParam = v
}

func (o CardAuthorizeRequestAccountParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if true {
		toSerialize["cardParam"] = o.CardParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardAuthorizeRequestAccountParam struct {
	value *CardAuthorizeRequestAccountParam
	isSet bool
}

func (v NullableCardAuthorizeRequestAccountParam) Get() *CardAuthorizeRequestAccountParam {
	return v.value
}

func (v *NullableCardAuthorizeRequestAccountParam) Set(val *CardAuthorizeRequestAccountParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardAuthorizeRequestAccountParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardAuthorizeRequestAccountParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardAuthorizeRequestAccountParam(val *CardAuthorizeRequestAccountParam) *NullableCardAuthorizeRequestAccountParam {
	return &NullableCardAuthorizeRequestAccountParam{value: val, isSet: true}
}

func (v NullableCardAuthorizeRequestAccountParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardAuthorizeRequestAccountParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


