/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountAddRequestParamsAllOfPayNowIdParamAccountParam struct for AccountAddRequestParamsAllOfPayNowIdParamAccountParam
type AccountAddRequestParamsAllOfPayNowIdParamAccountParam struct {
	AccountId string `json:"accountId"`
}

// NewAccountAddRequestParamsAllOfPayNowIdParamAccountParam instantiates a new AccountAddRequestParamsAllOfPayNowIdParamAccountParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountAddRequestParamsAllOfPayNowIdParamAccountParam(accountId string) *AccountAddRequestParamsAllOfPayNowIdParamAccountParam {
	this := AccountAddRequestParamsAllOfPayNowIdParamAccountParam{}
	this.AccountId = accountId
	return &this
}

// NewAccountAddRequestParamsAllOfPayNowIdParamAccountParamWithDefaults instantiates a new AccountAddRequestParamsAllOfPayNowIdParamAccountParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountAddRequestParamsAllOfPayNowIdParamAccountParamWithDefaults() *AccountAddRequestParamsAllOfPayNowIdParamAccountParam {
	this := AccountAddRequestParamsAllOfPayNowIdParamAccountParam{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AccountAddRequestParamsAllOfPayNowIdParamAccountParam) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AccountAddRequestParamsAllOfPayNowIdParamAccountParam) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AccountAddRequestParamsAllOfPayNowIdParamAccountParam) SetAccountId(v string) {
	o.AccountId = v
}

func (o AccountAddRequestParamsAllOfPayNowIdParamAccountParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam struct {
	value *AccountAddRequestParamsAllOfPayNowIdParamAccountParam
	isSet bool
}

func (v NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam) Get() *AccountAddRequestParamsAllOfPayNowIdParamAccountParam {
	return v.value
}

func (v *NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam) Set(val *AccountAddRequestParamsAllOfPayNowIdParamAccountParam) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam(val *AccountAddRequestParamsAllOfPayNowIdParamAccountParam) *NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam {
	return &NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam{value: val, isSet: true}
}

func (v NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountAddRequestParamsAllOfPayNowIdParamAccountParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


