/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardAuthorizeRequestParamsAllOfPayNowIdParam struct for CardAuthorizeRequestParamsAllOfPayNowIdParam
type CardAuthorizeRequestParamsAllOfPayNowIdParam struct {
	AccountParam CardAuthorizeRequestAccountParam `json:"accountParam"`
}

// NewCardAuthorizeRequestParamsAllOfPayNowIdParam instantiates a new CardAuthorizeRequestParamsAllOfPayNowIdParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardAuthorizeRequestParamsAllOfPayNowIdParam(accountParam CardAuthorizeRequestAccountParam) *CardAuthorizeRequestParamsAllOfPayNowIdParam {
	this := CardAuthorizeRequestParamsAllOfPayNowIdParam{}
	this.AccountParam = accountParam
	return &this
}

// NewCardAuthorizeRequestParamsAllOfPayNowIdParamWithDefaults instantiates a new CardAuthorizeRequestParamsAllOfPayNowIdParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardAuthorizeRequestParamsAllOfPayNowIdParamWithDefaults() *CardAuthorizeRequestParamsAllOfPayNowIdParam {
	this := CardAuthorizeRequestParamsAllOfPayNowIdParam{}
	return &this
}

// GetAccountParam returns the AccountParam field value
func (o *CardAuthorizeRequestParamsAllOfPayNowIdParam) GetAccountParam() CardAuthorizeRequestAccountParam {
	if o == nil {
		var ret CardAuthorizeRequestAccountParam
		return ret
	}

	return o.AccountParam
}

// GetAccountParamOk returns a tuple with the AccountParam field value
// and a boolean to check if the value has been set.
func (o *CardAuthorizeRequestParamsAllOfPayNowIdParam) GetAccountParamOk() (*CardAuthorizeRequestAccountParam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountParam, true
}

// SetAccountParam sets field value
func (o *CardAuthorizeRequestParamsAllOfPayNowIdParam) SetAccountParam(v CardAuthorizeRequestAccountParam) {
	o.AccountParam = v
}

func (o CardAuthorizeRequestParamsAllOfPayNowIdParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountParam"] = o.AccountParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardAuthorizeRequestParamsAllOfPayNowIdParam struct {
	value *CardAuthorizeRequestParamsAllOfPayNowIdParam
	isSet bool
}

func (v NullableCardAuthorizeRequestParamsAllOfPayNowIdParam) Get() *CardAuthorizeRequestParamsAllOfPayNowIdParam {
	return v.value
}

func (v *NullableCardAuthorizeRequestParamsAllOfPayNowIdParam) Set(val *CardAuthorizeRequestParamsAllOfPayNowIdParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardAuthorizeRequestParamsAllOfPayNowIdParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardAuthorizeRequestParamsAllOfPayNowIdParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardAuthorizeRequestParamsAllOfPayNowIdParam(val *CardAuthorizeRequestParamsAllOfPayNowIdParam) *NullableCardAuthorizeRequestParamsAllOfPayNowIdParam {
	return &NullableCardAuthorizeRequestParamsAllOfPayNowIdParam{value: val, isSet: true}
}

func (v NullableCardAuthorizeRequestParamsAllOfPayNowIdParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardAuthorizeRequestParamsAllOfPayNowIdParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


