/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoUpdateRequestAllOf struct for CardInfoUpdateRequestAllOf
type CardInfoUpdateRequestAllOf struct {
	AccountId *string `json:"accountId,omitempty"`
	CardId *string `json:"cardId,omitempty"`
	CardNumber *string `json:"cardNumber,omitempty"`
	CardExpire *string `json:"cardExpire,omitempty"`
	SecurityCode *string `json:"securityCode,omitempty"`
}

// NewCardInfoUpdateRequestAllOf instantiates a new CardInfoUpdateRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoUpdateRequestAllOf() *CardInfoUpdateRequestAllOf {
	this := CardInfoUpdateRequestAllOf{}
	return &this
}

// NewCardInfoUpdateRequestAllOfWithDefaults instantiates a new CardInfoUpdateRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoUpdateRequestAllOfWithDefaults() *CardInfoUpdateRequestAllOf {
	this := CardInfoUpdateRequestAllOf{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CardInfoUpdateRequestAllOf) GetAccountId() string {
	if o == nil || o.AccountId == nil {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequestAllOf) GetAccountIdOk() (*string, bool) {
	if o == nil || o.AccountId == nil {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CardInfoUpdateRequestAllOf) HasAccountId() bool {
	if o != nil && o.AccountId != nil {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CardInfoUpdateRequestAllOf) SetAccountId(v string) {
	o.AccountId = &v
}

// GetCardId returns the CardId field value if set, zero value otherwise.
func (o *CardInfoUpdateRequestAllOf) GetCardId() string {
	if o == nil || o.CardId == nil {
		var ret string
		return ret
	}
	return *o.CardId
}

// GetCardIdOk returns a tuple with the CardId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequestAllOf) GetCardIdOk() (*string, bool) {
	if o == nil || o.CardId == nil {
		return nil, false
	}
	return o.CardId, true
}

// HasCardId returns a boolean if a field has been set.
func (o *CardInfoUpdateRequestAllOf) HasCardId() bool {
	if o != nil && o.CardId != nil {
		return true
	}

	return false
}

// SetCardId gets a reference to the given string and assigns it to the CardId field.
func (o *CardInfoUpdateRequestAllOf) SetCardId(v string) {
	o.CardId = &v
}

// GetCardNumber returns the CardNumber field value if set, zero value otherwise.
func (o *CardInfoUpdateRequestAllOf) GetCardNumber() string {
	if o == nil || o.CardNumber == nil {
		var ret string
		return ret
	}
	return *o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequestAllOf) GetCardNumberOk() (*string, bool) {
	if o == nil || o.CardNumber == nil {
		return nil, false
	}
	return o.CardNumber, true
}

// HasCardNumber returns a boolean if a field has been set.
func (o *CardInfoUpdateRequestAllOf) HasCardNumber() bool {
	if o != nil && o.CardNumber != nil {
		return true
	}

	return false
}

// SetCardNumber gets a reference to the given string and assigns it to the CardNumber field.
func (o *CardInfoUpdateRequestAllOf) SetCardNumber(v string) {
	o.CardNumber = &v
}

// GetCardExpire returns the CardExpire field value if set, zero value otherwise.
func (o *CardInfoUpdateRequestAllOf) GetCardExpire() string {
	if o == nil || o.CardExpire == nil {
		var ret string
		return ret
	}
	return *o.CardExpire
}

// GetCardExpireOk returns a tuple with the CardExpire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequestAllOf) GetCardExpireOk() (*string, bool) {
	if o == nil || o.CardExpire == nil {
		return nil, false
	}
	return o.CardExpire, true
}

// HasCardExpire returns a boolean if a field has been set.
func (o *CardInfoUpdateRequestAllOf) HasCardExpire() bool {
	if o != nil && o.CardExpire != nil {
		return true
	}

	return false
}

// SetCardExpire gets a reference to the given string and assigns it to the CardExpire field.
func (o *CardInfoUpdateRequestAllOf) SetCardExpire(v string) {
	o.CardExpire = &v
}

// GetSecurityCode returns the SecurityCode field value if set, zero value otherwise.
func (o *CardInfoUpdateRequestAllOf) GetSecurityCode() string {
	if o == nil || o.SecurityCode == nil {
		var ret string
		return ret
	}
	return *o.SecurityCode
}

// GetSecurityCodeOk returns a tuple with the SecurityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequestAllOf) GetSecurityCodeOk() (*string, bool) {
	if o == nil || o.SecurityCode == nil {
		return nil, false
	}
	return o.SecurityCode, true
}

// HasSecurityCode returns a boolean if a field has been set.
func (o *CardInfoUpdateRequestAllOf) HasSecurityCode() bool {
	if o != nil && o.SecurityCode != nil {
		return true
	}

	return false
}

// SetSecurityCode gets a reference to the given string and assigns it to the SecurityCode field.
func (o *CardInfoUpdateRequestAllOf) SetSecurityCode(v string) {
	o.SecurityCode = &v
}

func (o CardInfoUpdateRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountId != nil {
		toSerialize["accountId"] = o.AccountId
	}
	if o.CardId != nil {
		toSerialize["cardId"] = o.CardId
	}
	if o.CardNumber != nil {
		toSerialize["cardNumber"] = o.CardNumber
	}
	if o.CardExpire != nil {
		toSerialize["cardExpire"] = o.CardExpire
	}
	if o.SecurityCode != nil {
		toSerialize["securityCode"] = o.SecurityCode
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoUpdateRequestAllOf struct {
	value *CardInfoUpdateRequestAllOf
	isSet bool
}

func (v NullableCardInfoUpdateRequestAllOf) Get() *CardInfoUpdateRequestAllOf {
	return v.value
}

func (v *NullableCardInfoUpdateRequestAllOf) Set(val *CardInfoUpdateRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoUpdateRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoUpdateRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoUpdateRequestAllOf(val *CardInfoUpdateRequestAllOf) *NullableCardInfoUpdateRequestAllOf {
	return &NullableCardInfoUpdateRequestAllOf{value: val, isSet: true}
}

func (v NullableCardInfoUpdateRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoUpdateRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


