/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardCancelRequest struct for CardCancelRequest
type CardCancelRequest struct {
	Params CardCancelRequestParams `json:"params"`
	AuthHash string `json:"authHash"`
}

// NewCardCancelRequest instantiates a new CardCancelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardCancelRequest(params CardCancelRequestParams, authHash string) *CardCancelRequest {
	this := CardCancelRequest{}
	this.Params = params
	this.AuthHash = authHash
	return &this
}

// NewCardCancelRequestWithDefaults instantiates a new CardCancelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardCancelRequestWithDefaults() *CardCancelRequest {
	this := CardCancelRequest{}
	return &this
}

// GetParams returns the Params field value
func (o *CardCancelRequest) GetParams() CardCancelRequestParams {
	if o == nil {
		var ret CardCancelRequestParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *CardCancelRequest) GetParamsOk() (*CardCancelRequestParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *CardCancelRequest) SetParams(v CardCancelRequestParams) {
	o.Params = v
}

// GetAuthHash returns the AuthHash field value
func (o *CardCancelRequest) GetAuthHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthHash
}

// GetAuthHashOk returns a tuple with the AuthHash field value
// and a boolean to check if the value has been set.
func (o *CardCancelRequest) GetAuthHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthHash, true
}

// SetAuthHash sets field value
func (o *CardCancelRequest) SetAuthHash(v string) {
	o.AuthHash = v
}

func (o CardCancelRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["params"] = o.Params
	}
	if true {
		toSerialize["authHash"] = o.AuthHash
	}
	return json.Marshal(toSerialize)
}

type NullableCardCancelRequest struct {
	value *CardCancelRequest
	isSet bool
}

func (v NullableCardCancelRequest) Get() *CardCancelRequest {
	return v.value
}

func (v *NullableCardCancelRequest) Set(val *CardCancelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardCancelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardCancelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardCancelRequest(val *CardCancelRequest) *NullableCardCancelRequest {
	return &NullableCardCancelRequest{value: val, isSet: true}
}

func (v NullableCardCancelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardCancelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


