/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam struct for CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam
type CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam struct {
	AccountId string `json:"accountId"`
}

// NewCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam instantiates a new CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam(accountId string) *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam {
	this := CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam{}
	this.AccountId = accountId
	return &this
}

// NewCardInfoGetRequestParamsAllOfPayNowIdParamAccountParamWithDefaults instantiates a new CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoGetRequestParamsAllOfPayNowIdParamAccountParamWithDefaults() *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam {
	this := CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) SetAccountId(v string) {
	o.AccountId = v
}

func (o CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam struct {
	value *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam
	isSet bool
}

func (v NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) Get() *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam {
	return v.value
}

func (v *NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) Set(val *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam(val *CardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) *NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam {
	return &NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam{value: val, isSet: true}
}

func (v NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoGetRequestParamsAllOfPayNowIdParamAccountParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


