/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountV1 会員情報
type AccountV1 struct {
	AccountId string `json:"accountId"`
	CardInfo []CardInfoV1 `json:"cardInfo,omitempty"`
}

// NewAccountV1 instantiates a new AccountV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountV1(accountId string) *AccountV1 {
	this := AccountV1{}
	this.AccountId = accountId
	return &this
}

// NewAccountV1WithDefaults instantiates a new AccountV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountV1WithDefaults() *AccountV1 {
	this := AccountV1{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AccountV1) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AccountV1) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AccountV1) SetAccountId(v string) {
	o.AccountId = v
}

// GetCardInfo returns the CardInfo field value if set, zero value otherwise.
func (o *AccountV1) GetCardInfo() []CardInfoV1 {
	if o == nil || o.CardInfo == nil {
		var ret []CardInfoV1
		return ret
	}
	return o.CardInfo
}

// GetCardInfoOk returns a tuple with the CardInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountV1) GetCardInfoOk() ([]CardInfoV1, bool) {
	if o == nil || o.CardInfo == nil {
		return nil, false
	}
	return o.CardInfo, true
}

// HasCardInfo returns a boolean if a field has been set.
func (o *AccountV1) HasCardInfo() bool {
	if o != nil && o.CardInfo != nil {
		return true
	}

	return false
}

// SetCardInfo gets a reference to the given []CardInfoV1 and assigns it to the CardInfo field.
func (o *AccountV1) SetCardInfo(v []CardInfoV1) {
	o.CardInfo = v
}

func (o AccountV1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if o.CardInfo != nil {
		toSerialize["cardInfo"] = o.CardInfo
	}
	return json.Marshal(toSerialize)
}

type NullableAccountV1 struct {
	value *AccountV1
	isSet bool
}

func (v NullableAccountV1) Get() *AccountV1 {
	return v.value
}

func (v *NullableAccountV1) Set(val *AccountV1) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountV1) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountV1(val *AccountV1) *NullableAccountV1 {
	return &NullableAccountV1{value: val, isSet: true}
}

func (v NullableAccountV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


