/*
Veritrance API

Veritrance API 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountAddResponsePayNowIdResponse struct for AccountAddResponsePayNowIdResponse
type AccountAddResponsePayNowIdResponse struct {
	// 会員管理処理を一意に識別する番号
	ProcessId string `json:"processId"`
	// 会員管理処理要求の実行結果
	Status string `json:"status"`
	// 会員管理処理要求の実行結果メッセージ
	Message string `json:"message"`
	Account *AccountV2 `json:"account,omitempty"`
}

// NewAccountAddResponsePayNowIdResponse instantiates a new AccountAddResponsePayNowIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountAddResponsePayNowIdResponse(processId string, status string, message string) *AccountAddResponsePayNowIdResponse {
	this := AccountAddResponsePayNowIdResponse{}
	this.ProcessId = processId
	this.Status = status
	this.Message = message
	return &this
}

// NewAccountAddResponsePayNowIdResponseWithDefaults instantiates a new AccountAddResponsePayNowIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountAddResponsePayNowIdResponseWithDefaults() *AccountAddResponsePayNowIdResponse {
	this := AccountAddResponsePayNowIdResponse{}
	return &this
}

// GetProcessId returns the ProcessId field value
func (o *AccountAddResponsePayNowIdResponse) GetProcessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessId
}

// GetProcessIdOk returns a tuple with the ProcessId field value
// and a boolean to check if the value has been set.
func (o *AccountAddResponsePayNowIdResponse) GetProcessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessId, true
}

// SetProcessId sets field value
func (o *AccountAddResponsePayNowIdResponse) SetProcessId(v string) {
	o.ProcessId = v
}

// GetStatus returns the Status field value
func (o *AccountAddResponsePayNowIdResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AccountAddResponsePayNowIdResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AccountAddResponsePayNowIdResponse) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *AccountAddResponsePayNowIdResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AccountAddResponsePayNowIdResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AccountAddResponsePayNowIdResponse) SetMessage(v string) {
	o.Message = v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *AccountAddResponsePayNowIdResponse) GetAccount() AccountV2 {
	if o == nil || o.Account == nil {
		var ret AccountV2
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAddResponsePayNowIdResponse) GetAccountOk() (*AccountV2, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *AccountAddResponsePayNowIdResponse) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given AccountV2 and assigns it to the Account field.
func (o *AccountAddResponsePayNowIdResponse) SetAccount(v AccountV2) {
	o.Account = &v
}

func (o AccountAddResponsePayNowIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["processId"] = o.ProcessId
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["message"] = o.Message
	}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	return json.Marshal(toSerialize)
}

type NullableAccountAddResponsePayNowIdResponse struct {
	value *AccountAddResponsePayNowIdResponse
	isSet bool
}

func (v NullableAccountAddResponsePayNowIdResponse) Get() *AccountAddResponsePayNowIdResponse {
	return v.value
}

func (v *NullableAccountAddResponsePayNowIdResponse) Set(val *AccountAddResponsePayNowIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountAddResponsePayNowIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountAddResponsePayNowIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountAddResponsePayNowIdResponse(val *AccountAddResponsePayNowIdResponse) *NullableAccountAddResponsePayNowIdResponse {
	return &NullableAccountAddResponsePayNowIdResponse{value: val, isSet: true}
}

func (v NullableAccountAddResponsePayNowIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountAddResponsePayNowIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


