/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
	"time"
)

// CardAuthorizeResponse struct for CardAuthorizeResponse
type CardAuthorizeResponse struct {
	// 要求電文を送信した決済サービスタイプ
	ServiceType *string `json:"serviceType,omitempty"`
	// 処理結果コード
	Status *string `json:"status,omitempty"`
	// 処理の結果を詳細に表すコード 4 桁ずつ 4 つのブロックで構成され、各ブロックでサービス毎の処理結果を表します。 
	VResultCode *string `json:"vResultCode,omitempty"`
	// 処理結果を日本語で表示します。
	MerrMsg *string `json:"merrMsg,omitempty"`
	// 決済サーバーにて決済処理電文（内部処理も含む）毎に付与する ID １つの取引 ID に対して、複数の ID が付与されます。 
	MarchTxn *string `json:"marchTxn,omitempty"`
	// 決済要求時に店舗様にて任意に採番し送信された取引 ID
	OrderId *string `json:"orderId,omitempty"`
	// 決済サーバーがオーダー（取引 ID）と紐付ける為に採番する ID
	CustTxn *string `json:"custTxn,omitempty"`
	// 電文のバージョン
	TxnVersion *string `json:"txnVersion,omitempty"`
	CardTransactiontype *string `json:"cardTransactiontype,omitempty"`
	GatewayRequestDate *time.Time `json:"gatewayRequestDate,omitempty"`
	GatewayResponseDate *time.Time `json:"gatewayResponseDate,omitempty"`
	CenterRequestDate *time.Time `json:"centerRequestDate,omitempty"`
	CenterResponseDate *time.Time `json:"centerResponseDate,omitempty"`
	Pending *int32 `json:"pending,omitempty"`
	Loopback *int32 `json:"loopback,omitempty"`
	ConnectedCenterId *string `json:"connectedCenterId,omitempty"`
	CenterRequestNumber *string `json:"centerRequestNumber,omitempty"`
	CenterReferenceNumber *string `json:"centerReferenceNumber,omitempty"`
	ResReturnReferenceNumber *string `json:"resReturnReferenceNumber,omitempty"`
	ResAuthCode *string `json:"resAuthCode,omitempty"`
	ResActionCode *string `json:"resActionCode,omitempty"`
	ResCenterErrorCode *string `json:"resCenterErrorCode,omitempty"`
	AcquirerCode *string `json:"acquirerCode,omitempty"`
}

// NewCardAuthorizeResponse instantiates a new CardAuthorizeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardAuthorizeResponse() *CardAuthorizeResponse {
	this := CardAuthorizeResponse{}
	return &this
}

// NewCardAuthorizeResponseWithDefaults instantiates a new CardAuthorizeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardAuthorizeResponseWithDefaults() *CardAuthorizeResponse {
	this := CardAuthorizeResponse{}
	return &this
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetServiceType() string {
	if o == nil || o.ServiceType == nil {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetServiceTypeOk() (*string, bool) {
	if o == nil || o.ServiceType == nil {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasServiceType() bool {
	if o != nil && o.ServiceType != nil {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *CardAuthorizeResponse) SetServiceType(v string) {
	o.ServiceType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CardAuthorizeResponse) SetStatus(v string) {
	o.Status = &v
}

// GetVResultCode returns the VResultCode field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetVResultCode() string {
	if o == nil || o.VResultCode == nil {
		var ret string
		return ret
	}
	return *o.VResultCode
}

// GetVResultCodeOk returns a tuple with the VResultCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetVResultCodeOk() (*string, bool) {
	if o == nil || o.VResultCode == nil {
		return nil, false
	}
	return o.VResultCode, true
}

// HasVResultCode returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasVResultCode() bool {
	if o != nil && o.VResultCode != nil {
		return true
	}

	return false
}

// SetVResultCode gets a reference to the given string and assigns it to the VResultCode field.
func (o *CardAuthorizeResponse) SetVResultCode(v string) {
	o.VResultCode = &v
}

// GetMerrMsg returns the MerrMsg field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetMerrMsg() string {
	if o == nil || o.MerrMsg == nil {
		var ret string
		return ret
	}
	return *o.MerrMsg
}

// GetMerrMsgOk returns a tuple with the MerrMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetMerrMsgOk() (*string, bool) {
	if o == nil || o.MerrMsg == nil {
		return nil, false
	}
	return o.MerrMsg, true
}

// HasMerrMsg returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasMerrMsg() bool {
	if o != nil && o.MerrMsg != nil {
		return true
	}

	return false
}

// SetMerrMsg gets a reference to the given string and assigns it to the MerrMsg field.
func (o *CardAuthorizeResponse) SetMerrMsg(v string) {
	o.MerrMsg = &v
}

// GetMarchTxn returns the MarchTxn field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetMarchTxn() string {
	if o == nil || o.MarchTxn == nil {
		var ret string
		return ret
	}
	return *o.MarchTxn
}

// GetMarchTxnOk returns a tuple with the MarchTxn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetMarchTxnOk() (*string, bool) {
	if o == nil || o.MarchTxn == nil {
		return nil, false
	}
	return o.MarchTxn, true
}

// HasMarchTxn returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasMarchTxn() bool {
	if o != nil && o.MarchTxn != nil {
		return true
	}

	return false
}

// SetMarchTxn gets a reference to the given string and assigns it to the MarchTxn field.
func (o *CardAuthorizeResponse) SetMarchTxn(v string) {
	o.MarchTxn = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetOrderId() string {
	if o == nil || o.OrderId == nil {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetOrderIdOk() (*string, bool) {
	if o == nil || o.OrderId == nil {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasOrderId() bool {
	if o != nil && o.OrderId != nil {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *CardAuthorizeResponse) SetOrderId(v string) {
	o.OrderId = &v
}

// GetCustTxn returns the CustTxn field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetCustTxn() string {
	if o == nil || o.CustTxn == nil {
		var ret string
		return ret
	}
	return *o.CustTxn
}

// GetCustTxnOk returns a tuple with the CustTxn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetCustTxnOk() (*string, bool) {
	if o == nil || o.CustTxn == nil {
		return nil, false
	}
	return o.CustTxn, true
}

// HasCustTxn returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasCustTxn() bool {
	if o != nil && o.CustTxn != nil {
		return true
	}

	return false
}

// SetCustTxn gets a reference to the given string and assigns it to the CustTxn field.
func (o *CardAuthorizeResponse) SetCustTxn(v string) {
	o.CustTxn = &v
}

// GetTxnVersion returns the TxnVersion field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetTxnVersion() string {
	if o == nil || o.TxnVersion == nil {
		var ret string
		return ret
	}
	return *o.TxnVersion
}

// GetTxnVersionOk returns a tuple with the TxnVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetTxnVersionOk() (*string, bool) {
	if o == nil || o.TxnVersion == nil {
		return nil, false
	}
	return o.TxnVersion, true
}

// HasTxnVersion returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasTxnVersion() bool {
	if o != nil && o.TxnVersion != nil {
		return true
	}

	return false
}

// SetTxnVersion gets a reference to the given string and assigns it to the TxnVersion field.
func (o *CardAuthorizeResponse) SetTxnVersion(v string) {
	o.TxnVersion = &v
}

// GetCardTransactiontype returns the CardTransactiontype field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetCardTransactiontype() string {
	if o == nil || o.CardTransactiontype == nil {
		var ret string
		return ret
	}
	return *o.CardTransactiontype
}

// GetCardTransactiontypeOk returns a tuple with the CardTransactiontype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetCardTransactiontypeOk() (*string, bool) {
	if o == nil || o.CardTransactiontype == nil {
		return nil, false
	}
	return o.CardTransactiontype, true
}

// HasCardTransactiontype returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasCardTransactiontype() bool {
	if o != nil && o.CardTransactiontype != nil {
		return true
	}

	return false
}

// SetCardTransactiontype gets a reference to the given string and assigns it to the CardTransactiontype field.
func (o *CardAuthorizeResponse) SetCardTransactiontype(v string) {
	o.CardTransactiontype = &v
}

// GetGatewayRequestDate returns the GatewayRequestDate field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetGatewayRequestDate() time.Time {
	if o == nil || o.GatewayRequestDate == nil {
		var ret time.Time
		return ret
	}
	return *o.GatewayRequestDate
}

// GetGatewayRequestDateOk returns a tuple with the GatewayRequestDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetGatewayRequestDateOk() (*time.Time, bool) {
	if o == nil || o.GatewayRequestDate == nil {
		return nil, false
	}
	return o.GatewayRequestDate, true
}

// HasGatewayRequestDate returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasGatewayRequestDate() bool {
	if o != nil && o.GatewayRequestDate != nil {
		return true
	}

	return false
}

// SetGatewayRequestDate gets a reference to the given time.Time and assigns it to the GatewayRequestDate field.
func (o *CardAuthorizeResponse) SetGatewayRequestDate(v time.Time) {
	o.GatewayRequestDate = &v
}

// GetGatewayResponseDate returns the GatewayResponseDate field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetGatewayResponseDate() time.Time {
	if o == nil || o.GatewayResponseDate == nil {
		var ret time.Time
		return ret
	}
	return *o.GatewayResponseDate
}

// GetGatewayResponseDateOk returns a tuple with the GatewayResponseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetGatewayResponseDateOk() (*time.Time, bool) {
	if o == nil || o.GatewayResponseDate == nil {
		return nil, false
	}
	return o.GatewayResponseDate, true
}

// HasGatewayResponseDate returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasGatewayResponseDate() bool {
	if o != nil && o.GatewayResponseDate != nil {
		return true
	}

	return false
}

// SetGatewayResponseDate gets a reference to the given time.Time and assigns it to the GatewayResponseDate field.
func (o *CardAuthorizeResponse) SetGatewayResponseDate(v time.Time) {
	o.GatewayResponseDate = &v
}

// GetCenterRequestDate returns the CenterRequestDate field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetCenterRequestDate() time.Time {
	if o == nil || o.CenterRequestDate == nil {
		var ret time.Time
		return ret
	}
	return *o.CenterRequestDate
}

// GetCenterRequestDateOk returns a tuple with the CenterRequestDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetCenterRequestDateOk() (*time.Time, bool) {
	if o == nil || o.CenterRequestDate == nil {
		return nil, false
	}
	return o.CenterRequestDate, true
}

// HasCenterRequestDate returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasCenterRequestDate() bool {
	if o != nil && o.CenterRequestDate != nil {
		return true
	}

	return false
}

// SetCenterRequestDate gets a reference to the given time.Time and assigns it to the CenterRequestDate field.
func (o *CardAuthorizeResponse) SetCenterRequestDate(v time.Time) {
	o.CenterRequestDate = &v
}

// GetCenterResponseDate returns the CenterResponseDate field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetCenterResponseDate() time.Time {
	if o == nil || o.CenterResponseDate == nil {
		var ret time.Time
		return ret
	}
	return *o.CenterResponseDate
}

// GetCenterResponseDateOk returns a tuple with the CenterResponseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetCenterResponseDateOk() (*time.Time, bool) {
	if o == nil || o.CenterResponseDate == nil {
		return nil, false
	}
	return o.CenterResponseDate, true
}

// HasCenterResponseDate returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasCenterResponseDate() bool {
	if o != nil && o.CenterResponseDate != nil {
		return true
	}

	return false
}

// SetCenterResponseDate gets a reference to the given time.Time and assigns it to the CenterResponseDate field.
func (o *CardAuthorizeResponse) SetCenterResponseDate(v time.Time) {
	o.CenterResponseDate = &v
}

// GetPending returns the Pending field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetPending() int32 {
	if o == nil || o.Pending == nil {
		var ret int32
		return ret
	}
	return *o.Pending
}

// GetPendingOk returns a tuple with the Pending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetPendingOk() (*int32, bool) {
	if o == nil || o.Pending == nil {
		return nil, false
	}
	return o.Pending, true
}

// HasPending returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasPending() bool {
	if o != nil && o.Pending != nil {
		return true
	}

	return false
}

// SetPending gets a reference to the given int32 and assigns it to the Pending field.
func (o *CardAuthorizeResponse) SetPending(v int32) {
	o.Pending = &v
}

// GetLoopback returns the Loopback field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetLoopback() int32 {
	if o == nil || o.Loopback == nil {
		var ret int32
		return ret
	}
	return *o.Loopback
}

// GetLoopbackOk returns a tuple with the Loopback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetLoopbackOk() (*int32, bool) {
	if o == nil || o.Loopback == nil {
		return nil, false
	}
	return o.Loopback, true
}

// HasLoopback returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasLoopback() bool {
	if o != nil && o.Loopback != nil {
		return true
	}

	return false
}

// SetLoopback gets a reference to the given int32 and assigns it to the Loopback field.
func (o *CardAuthorizeResponse) SetLoopback(v int32) {
	o.Loopback = &v
}

// GetConnectedCenterId returns the ConnectedCenterId field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetConnectedCenterId() string {
	if o == nil || o.ConnectedCenterId == nil {
		var ret string
		return ret
	}
	return *o.ConnectedCenterId
}

// GetConnectedCenterIdOk returns a tuple with the ConnectedCenterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetConnectedCenterIdOk() (*string, bool) {
	if o == nil || o.ConnectedCenterId == nil {
		return nil, false
	}
	return o.ConnectedCenterId, true
}

// HasConnectedCenterId returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasConnectedCenterId() bool {
	if o != nil && o.ConnectedCenterId != nil {
		return true
	}

	return false
}

// SetConnectedCenterId gets a reference to the given string and assigns it to the ConnectedCenterId field.
func (o *CardAuthorizeResponse) SetConnectedCenterId(v string) {
	o.ConnectedCenterId = &v
}

// GetCenterRequestNumber returns the CenterRequestNumber field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetCenterRequestNumber() string {
	if o == nil || o.CenterRequestNumber == nil {
		var ret string
		return ret
	}
	return *o.CenterRequestNumber
}

// GetCenterRequestNumberOk returns a tuple with the CenterRequestNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetCenterRequestNumberOk() (*string, bool) {
	if o == nil || o.CenterRequestNumber == nil {
		return nil, false
	}
	return o.CenterRequestNumber, true
}

// HasCenterRequestNumber returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasCenterRequestNumber() bool {
	if o != nil && o.CenterRequestNumber != nil {
		return true
	}

	return false
}

// SetCenterRequestNumber gets a reference to the given string and assigns it to the CenterRequestNumber field.
func (o *CardAuthorizeResponse) SetCenterRequestNumber(v string) {
	o.CenterRequestNumber = &v
}

// GetCenterReferenceNumber returns the CenterReferenceNumber field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetCenterReferenceNumber() string {
	if o == nil || o.CenterReferenceNumber == nil {
		var ret string
		return ret
	}
	return *o.CenterReferenceNumber
}

// GetCenterReferenceNumberOk returns a tuple with the CenterReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetCenterReferenceNumberOk() (*string, bool) {
	if o == nil || o.CenterReferenceNumber == nil {
		return nil, false
	}
	return o.CenterReferenceNumber, true
}

// HasCenterReferenceNumber returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasCenterReferenceNumber() bool {
	if o != nil && o.CenterReferenceNumber != nil {
		return true
	}

	return false
}

// SetCenterReferenceNumber gets a reference to the given string and assigns it to the CenterReferenceNumber field.
func (o *CardAuthorizeResponse) SetCenterReferenceNumber(v string) {
	o.CenterReferenceNumber = &v
}

// GetResReturnReferenceNumber returns the ResReturnReferenceNumber field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetResReturnReferenceNumber() string {
	if o == nil || o.ResReturnReferenceNumber == nil {
		var ret string
		return ret
	}
	return *o.ResReturnReferenceNumber
}

// GetResReturnReferenceNumberOk returns a tuple with the ResReturnReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetResReturnReferenceNumberOk() (*string, bool) {
	if o == nil || o.ResReturnReferenceNumber == nil {
		return nil, false
	}
	return o.ResReturnReferenceNumber, true
}

// HasResReturnReferenceNumber returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasResReturnReferenceNumber() bool {
	if o != nil && o.ResReturnReferenceNumber != nil {
		return true
	}

	return false
}

// SetResReturnReferenceNumber gets a reference to the given string and assigns it to the ResReturnReferenceNumber field.
func (o *CardAuthorizeResponse) SetResReturnReferenceNumber(v string) {
	o.ResReturnReferenceNumber = &v
}

// GetResAuthCode returns the ResAuthCode field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetResAuthCode() string {
	if o == nil || o.ResAuthCode == nil {
		var ret string
		return ret
	}
	return *o.ResAuthCode
}

// GetResAuthCodeOk returns a tuple with the ResAuthCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetResAuthCodeOk() (*string, bool) {
	if o == nil || o.ResAuthCode == nil {
		return nil, false
	}
	return o.ResAuthCode, true
}

// HasResAuthCode returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasResAuthCode() bool {
	if o != nil && o.ResAuthCode != nil {
		return true
	}

	return false
}

// SetResAuthCode gets a reference to the given string and assigns it to the ResAuthCode field.
func (o *CardAuthorizeResponse) SetResAuthCode(v string) {
	o.ResAuthCode = &v
}

// GetResActionCode returns the ResActionCode field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetResActionCode() string {
	if o == nil || o.ResActionCode == nil {
		var ret string
		return ret
	}
	return *o.ResActionCode
}

// GetResActionCodeOk returns a tuple with the ResActionCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetResActionCodeOk() (*string, bool) {
	if o == nil || o.ResActionCode == nil {
		return nil, false
	}
	return o.ResActionCode, true
}

// HasResActionCode returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasResActionCode() bool {
	if o != nil && o.ResActionCode != nil {
		return true
	}

	return false
}

// SetResActionCode gets a reference to the given string and assigns it to the ResActionCode field.
func (o *CardAuthorizeResponse) SetResActionCode(v string) {
	o.ResActionCode = &v
}

// GetResCenterErrorCode returns the ResCenterErrorCode field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetResCenterErrorCode() string {
	if o == nil || o.ResCenterErrorCode == nil {
		var ret string
		return ret
	}
	return *o.ResCenterErrorCode
}

// GetResCenterErrorCodeOk returns a tuple with the ResCenterErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetResCenterErrorCodeOk() (*string, bool) {
	if o == nil || o.ResCenterErrorCode == nil {
		return nil, false
	}
	return o.ResCenterErrorCode, true
}

// HasResCenterErrorCode returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasResCenterErrorCode() bool {
	if o != nil && o.ResCenterErrorCode != nil {
		return true
	}

	return false
}

// SetResCenterErrorCode gets a reference to the given string and assigns it to the ResCenterErrorCode field.
func (o *CardAuthorizeResponse) SetResCenterErrorCode(v string) {
	o.ResCenterErrorCode = &v
}

// GetAcquirerCode returns the AcquirerCode field value if set, zero value otherwise.
func (o *CardAuthorizeResponse) GetAcquirerCode() string {
	if o == nil || o.AcquirerCode == nil {
		var ret string
		return ret
	}
	return *o.AcquirerCode
}

// GetAcquirerCodeOk returns a tuple with the AcquirerCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeResponse) GetAcquirerCodeOk() (*string, bool) {
	if o == nil || o.AcquirerCode == nil {
		return nil, false
	}
	return o.AcquirerCode, true
}

// HasAcquirerCode returns a boolean if a field has been set.
func (o *CardAuthorizeResponse) HasAcquirerCode() bool {
	if o != nil && o.AcquirerCode != nil {
		return true
	}

	return false
}

// SetAcquirerCode gets a reference to the given string and assigns it to the AcquirerCode field.
func (o *CardAuthorizeResponse) SetAcquirerCode(v string) {
	o.AcquirerCode = &v
}

func (o CardAuthorizeResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ServiceType != nil {
		toSerialize["serviceType"] = o.ServiceType
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.VResultCode != nil {
		toSerialize["vResultCode"] = o.VResultCode
	}
	if o.MerrMsg != nil {
		toSerialize["merrMsg"] = o.MerrMsg
	}
	if o.MarchTxn != nil {
		toSerialize["marchTxn"] = o.MarchTxn
	}
	if o.OrderId != nil {
		toSerialize["orderId"] = o.OrderId
	}
	if o.CustTxn != nil {
		toSerialize["custTxn"] = o.CustTxn
	}
	if o.TxnVersion != nil {
		toSerialize["txnVersion"] = o.TxnVersion
	}
	if o.CardTransactiontype != nil {
		toSerialize["cardTransactiontype"] = o.CardTransactiontype
	}
	if o.GatewayRequestDate != nil {
		toSerialize["gatewayRequestDate"] = o.GatewayRequestDate
	}
	if o.GatewayResponseDate != nil {
		toSerialize["gatewayResponseDate"] = o.GatewayResponseDate
	}
	if o.CenterRequestDate != nil {
		toSerialize["centerRequestDate"] = o.CenterRequestDate
	}
	if o.CenterResponseDate != nil {
		toSerialize["centerResponseDate"] = o.CenterResponseDate
	}
	if o.Pending != nil {
		toSerialize["pending"] = o.Pending
	}
	if o.Loopback != nil {
		toSerialize["loopback"] = o.Loopback
	}
	if o.ConnectedCenterId != nil {
		toSerialize["connectedCenterId"] = o.ConnectedCenterId
	}
	if o.CenterRequestNumber != nil {
		toSerialize["centerRequestNumber"] = o.CenterRequestNumber
	}
	if o.CenterReferenceNumber != nil {
		toSerialize["centerReferenceNumber"] = o.CenterReferenceNumber
	}
	if o.ResReturnReferenceNumber != nil {
		toSerialize["resReturnReferenceNumber"] = o.ResReturnReferenceNumber
	}
	if o.ResAuthCode != nil {
		toSerialize["resAuthCode"] = o.ResAuthCode
	}
	if o.ResActionCode != nil {
		toSerialize["resActionCode"] = o.ResActionCode
	}
	if o.ResCenterErrorCode != nil {
		toSerialize["resCenterErrorCode"] = o.ResCenterErrorCode
	}
	if o.AcquirerCode != nil {
		toSerialize["acquirerCode"] = o.AcquirerCode
	}
	return json.Marshal(toSerialize)
}

type NullableCardAuthorizeResponse struct {
	value *CardAuthorizeResponse
	isSet bool
}

func (v NullableCardAuthorizeResponse) Get() *CardAuthorizeResponse {
	return v.value
}

func (v *NullableCardAuthorizeResponse) Set(val *CardAuthorizeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCardAuthorizeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCardAuthorizeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardAuthorizeResponse(val *CardAuthorizeResponse) *NullableCardAuthorizeResponse {
	return &NullableCardAuthorizeResponse{value: val, isSet: true}
}

func (v NullableCardAuthorizeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardAuthorizeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


