/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam struct for CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam
type CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam struct {
	AccountId string `json:"accountId"`
	CardParam CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam `json:"cardParam"`
}

// NewCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam instantiates a new CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam(accountId string, cardParam CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam {
	this := CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam{}
	this.AccountId = accountId
	this.CardParam = cardParam
	return &this
}

// NewCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamWithDefaults instantiates a new CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamWithDefaults() *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam {
	this := CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) SetAccountId(v string) {
	o.AccountId = v
}

// GetCardParam returns the CardParam field value
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) GetCardParam() CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam {
	if o == nil {
		var ret CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam
		return ret
	}

	return o.CardParam
}

// GetCardParamOk returns a tuple with the CardParam field value
// and a boolean to check if the value has been set.
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) GetCardParamOk() (*CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardParam, true
}

// SetCardParam sets field value
func (o *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) SetCardParam(v CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParamCardParam) {
	o.CardParam = v
}

func (o CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if true {
		toSerialize["cardParam"] = o.CardParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam struct {
	value *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam
	isSet bool
}

func (v NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) Get() *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam {
	return v.value
}

func (v *NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) Set(val *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam(val *CardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) *NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam {
	return &NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam{value: val, isSet: true}
}

func (v NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoDeleteRequestParamsAllOfPayNowIdParamAccountParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


