/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardCancelRequestAllOf struct for CardCancelRequestAllOf
type CardCancelRequestAllOf struct {
	OrderId *string `json:"orderId,omitempty"`
	Amount *string `json:"amount,omitempty"`
}

// NewCardCancelRequestAllOf instantiates a new CardCancelRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardCancelRequestAllOf() *CardCancelRequestAllOf {
	this := CardCancelRequestAllOf{}
	return &this
}

// NewCardCancelRequestAllOfWithDefaults instantiates a new CardCancelRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardCancelRequestAllOfWithDefaults() *CardCancelRequestAllOf {
	this := CardCancelRequestAllOf{}
	return &this
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *CardCancelRequestAllOf) GetOrderId() string {
	if o == nil || o.OrderId == nil {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardCancelRequestAllOf) GetOrderIdOk() (*string, bool) {
	if o == nil || o.OrderId == nil {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *CardCancelRequestAllOf) HasOrderId() bool {
	if o != nil && o.OrderId != nil {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *CardCancelRequestAllOf) SetOrderId(v string) {
	o.OrderId = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CardCancelRequestAllOf) GetAmount() string {
	if o == nil || o.Amount == nil {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardCancelRequestAllOf) GetAmountOk() (*string, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CardCancelRequestAllOf) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *CardCancelRequestAllOf) SetAmount(v string) {
	o.Amount = &v
}

func (o CardCancelRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OrderId != nil {
		toSerialize["orderId"] = o.OrderId
	}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableCardCancelRequestAllOf struct {
	value *CardCancelRequestAllOf
	isSet bool
}

func (v NullableCardCancelRequestAllOf) Get() *CardCancelRequestAllOf {
	return v.value
}

func (v *NullableCardCancelRequestAllOf) Set(val *CardCancelRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCardCancelRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCardCancelRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardCancelRequestAllOf(val *CardCancelRequestAllOf) *NullableCardCancelRequestAllOf {
	return &NullableCardCancelRequestAllOf{value: val, isSet: true}
}

func (v NullableCardCancelRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardCancelRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


