/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardReAuthorizeRequest struct for CardReAuthorizeRequest
type CardReAuthorizeRequest struct {
	Params CardReAuthorizeRequestParams `json:"params"`
	AuthHash string `json:"authHash"`
}

// NewCardReAuthorizeRequest instantiates a new CardReAuthorizeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardReAuthorizeRequest(params CardReAuthorizeRequestParams, authHash string) *CardReAuthorizeRequest {
	this := CardReAuthorizeRequest{}
	this.Params = params
	this.AuthHash = authHash
	return &this
}

// NewCardReAuthorizeRequestWithDefaults instantiates a new CardReAuthorizeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardReAuthorizeRequestWithDefaults() *CardReAuthorizeRequest {
	this := CardReAuthorizeRequest{}
	return &this
}

// GetParams returns the Params field value
func (o *CardReAuthorizeRequest) GetParams() CardReAuthorizeRequestParams {
	if o == nil {
		var ret CardReAuthorizeRequestParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *CardReAuthorizeRequest) GetParamsOk() (*CardReAuthorizeRequestParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *CardReAuthorizeRequest) SetParams(v CardReAuthorizeRequestParams) {
	o.Params = v
}

// GetAuthHash returns the AuthHash field value
func (o *CardReAuthorizeRequest) GetAuthHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthHash
}

// GetAuthHashOk returns a tuple with the AuthHash field value
// and a boolean to check if the value has been set.
func (o *CardReAuthorizeRequest) GetAuthHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthHash, true
}

// SetAuthHash sets field value
func (o *CardReAuthorizeRequest) SetAuthHash(v string) {
	o.AuthHash = v
}

func (o CardReAuthorizeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["params"] = o.Params
	}
	if true {
		toSerialize["authHash"] = o.AuthHash
	}
	return json.Marshal(toSerialize)
}

type NullableCardReAuthorizeRequest struct {
	value *CardReAuthorizeRequest
	isSet bool
}

func (v NullableCardReAuthorizeRequest) Get() *CardReAuthorizeRequest {
	return v.value
}

func (v *NullableCardReAuthorizeRequest) Set(val *CardReAuthorizeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardReAuthorizeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardReAuthorizeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardReAuthorizeRequest(val *CardReAuthorizeRequest) *NullableCardReAuthorizeRequest {
	return &NullableCardReAuthorizeRequest{value: val, isSet: true}
}

func (v NullableCardReAuthorizeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardReAuthorizeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


