/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardCaptureRequestParams struct for CardCaptureRequestParams
type CardCaptureRequestParams struct {
	TxnVersion string `json:"txnVersion"`
	DummyRequest string `json:"dummyRequest"`
	MerchantCcid string `json:"merchantCcid"`
	OrderId string `json:"orderId"`
	Amount string `json:"amount"`
	CurrencyUnit CurrencyUnit `json:"currencyUnit"`
}

// NewCardCaptureRequestParams instantiates a new CardCaptureRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardCaptureRequestParams(txnVersion string, dummyRequest string, merchantCcid string, orderId string, amount string, currencyUnit CurrencyUnit) *CardCaptureRequestParams {
	this := CardCaptureRequestParams{}
	this.TxnVersion = txnVersion
	this.DummyRequest = dummyRequest
	this.MerchantCcid = merchantCcid
	this.OrderId = orderId
	this.Amount = amount
	this.CurrencyUnit = currencyUnit
	return &this
}

// NewCardCaptureRequestParamsWithDefaults instantiates a new CardCaptureRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardCaptureRequestParamsWithDefaults() *CardCaptureRequestParams {
	this := CardCaptureRequestParams{}
	return &this
}

// GetTxnVersion returns the TxnVersion field value
func (o *CardCaptureRequestParams) GetTxnVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxnVersion
}

// GetTxnVersionOk returns a tuple with the TxnVersion field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestParams) GetTxnVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxnVersion, true
}

// SetTxnVersion sets field value
func (o *CardCaptureRequestParams) SetTxnVersion(v string) {
	o.TxnVersion = v
}

// GetDummyRequest returns the DummyRequest field value
func (o *CardCaptureRequestParams) GetDummyRequest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DummyRequest
}

// GetDummyRequestOk returns a tuple with the DummyRequest field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestParams) GetDummyRequestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DummyRequest, true
}

// SetDummyRequest sets field value
func (o *CardCaptureRequestParams) SetDummyRequest(v string) {
	o.DummyRequest = v
}

// GetMerchantCcid returns the MerchantCcid field value
func (o *CardCaptureRequestParams) GetMerchantCcid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantCcid
}

// GetMerchantCcidOk returns a tuple with the MerchantCcid field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestParams) GetMerchantCcidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantCcid, true
}

// SetMerchantCcid sets field value
func (o *CardCaptureRequestParams) SetMerchantCcid(v string) {
	o.MerchantCcid = v
}

// GetOrderId returns the OrderId field value
func (o *CardCaptureRequestParams) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestParams) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *CardCaptureRequestParams) SetOrderId(v string) {
	o.OrderId = v
}

// GetAmount returns the Amount field value
func (o *CardCaptureRequestParams) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestParams) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CardCaptureRequestParams) SetAmount(v string) {
	o.Amount = v
}

// GetCurrencyUnit returns the CurrencyUnit field value
func (o *CardCaptureRequestParams) GetCurrencyUnit() CurrencyUnit {
	if o == nil {
		var ret CurrencyUnit
		return ret
	}

	return o.CurrencyUnit
}

// GetCurrencyUnitOk returns a tuple with the CurrencyUnit field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestParams) GetCurrencyUnitOk() (*CurrencyUnit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyUnit, true
}

// SetCurrencyUnit sets field value
func (o *CardCaptureRequestParams) SetCurrencyUnit(v CurrencyUnit) {
	o.CurrencyUnit = v
}

func (o CardCaptureRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["txnVersion"] = o.TxnVersion
	}
	if true {
		toSerialize["dummyRequest"] = o.DummyRequest
	}
	if true {
		toSerialize["merchantCcid"] = o.MerchantCcid
	}
	if true {
		toSerialize["orderId"] = o.OrderId
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["currencyUnit"] = o.CurrencyUnit
	}
	return json.Marshal(toSerialize)
}

type NullableCardCaptureRequestParams struct {
	value *CardCaptureRequestParams
	isSet bool
}

func (v NullableCardCaptureRequestParams) Get() *CardCaptureRequestParams {
	return v.value
}

func (v *NullableCardCaptureRequestParams) Set(val *CardCaptureRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableCardCaptureRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableCardCaptureRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardCaptureRequestParams(val *CardCaptureRequestParams) *NullableCardCaptureRequestParams {
	return &NullableCardCaptureRequestParams{value: val, isSet: true}
}

func (v NullableCardCaptureRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardCaptureRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


