/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// AccountResponse struct for AccountResponse
type AccountResponse struct {
	PayNowIdResponse *AccountResponsePayNowIdResponse `json:"payNowIdResponse,omitempty"`
	// 要求電文を送信した決済サービスタイプ
	ServiceType *string `json:"serviceType,omitempty"`
	// 処理結果コード
	Status *string `json:"status,omitempty"`
	// 処理の結果を詳細に表すコード 4 桁ずつ 4 つのブロックで構成され、各ブロックでサービス毎の処理結果を表します。 
	VResultCode *string `json:"vResultCode,omitempty"`
	// 処理結果を日本語で表示します。
	MerrMsg *string `json:"merrMsg,omitempty"`
}

// NewAccountResponse instantiates a new AccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResponse() *AccountResponse {
	this := AccountResponse{}
	return &this
}

// NewAccountResponseWithDefaults instantiates a new AccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResponseWithDefaults() *AccountResponse {
	this := AccountResponse{}
	return &this
}

// GetPayNowIdResponse returns the PayNowIdResponse field value if set, zero value otherwise.
func (o *AccountResponse) GetPayNowIdResponse() AccountResponsePayNowIdResponse {
	if o == nil || o.PayNowIdResponse == nil {
		var ret AccountResponsePayNowIdResponse
		return ret
	}
	return *o.PayNowIdResponse
}

// GetPayNowIdResponseOk returns a tuple with the PayNowIdResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetPayNowIdResponseOk() (*AccountResponsePayNowIdResponse, bool) {
	if o == nil || o.PayNowIdResponse == nil {
		return nil, false
	}
	return o.PayNowIdResponse, true
}

// HasPayNowIdResponse returns a boolean if a field has been set.
func (o *AccountResponse) HasPayNowIdResponse() bool {
	if o != nil && o.PayNowIdResponse != nil {
		return true
	}

	return false
}

// SetPayNowIdResponse gets a reference to the given AccountResponsePayNowIdResponse and assigns it to the PayNowIdResponse field.
func (o *AccountResponse) SetPayNowIdResponse(v AccountResponsePayNowIdResponse) {
	o.PayNowIdResponse = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *AccountResponse) GetServiceType() string {
	if o == nil || o.ServiceType == nil {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetServiceTypeOk() (*string, bool) {
	if o == nil || o.ServiceType == nil {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *AccountResponse) HasServiceType() bool {
	if o != nil && o.ServiceType != nil {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *AccountResponse) SetServiceType(v string) {
	o.ServiceType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AccountResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AccountResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AccountResponse) SetStatus(v string) {
	o.Status = &v
}

// GetVResultCode returns the VResultCode field value if set, zero value otherwise.
func (o *AccountResponse) GetVResultCode() string {
	if o == nil || o.VResultCode == nil {
		var ret string
		return ret
	}
	return *o.VResultCode
}

// GetVResultCodeOk returns a tuple with the VResultCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetVResultCodeOk() (*string, bool) {
	if o == nil || o.VResultCode == nil {
		return nil, false
	}
	return o.VResultCode, true
}

// HasVResultCode returns a boolean if a field has been set.
func (o *AccountResponse) HasVResultCode() bool {
	if o != nil && o.VResultCode != nil {
		return true
	}

	return false
}

// SetVResultCode gets a reference to the given string and assigns it to the VResultCode field.
func (o *AccountResponse) SetVResultCode(v string) {
	o.VResultCode = &v
}

// GetMerrMsg returns the MerrMsg field value if set, zero value otherwise.
func (o *AccountResponse) GetMerrMsg() string {
	if o == nil || o.MerrMsg == nil {
		var ret string
		return ret
	}
	return *o.MerrMsg
}

// GetMerrMsgOk returns a tuple with the MerrMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetMerrMsgOk() (*string, bool) {
	if o == nil || o.MerrMsg == nil {
		return nil, false
	}
	return o.MerrMsg, true
}

// HasMerrMsg returns a boolean if a field has been set.
func (o *AccountResponse) HasMerrMsg() bool {
	if o != nil && o.MerrMsg != nil {
		return true
	}

	return false
}

// SetMerrMsg gets a reference to the given string and assigns it to the MerrMsg field.
func (o *AccountResponse) SetMerrMsg(v string) {
	o.MerrMsg = &v
}

func (o AccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PayNowIdResponse != nil {
		toSerialize["payNowIdResponse"] = o.PayNowIdResponse
	}
	if o.ServiceType != nil {
		toSerialize["serviceType"] = o.ServiceType
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.VResultCode != nil {
		toSerialize["vResultCode"] = o.VResultCode
	}
	if o.MerrMsg != nil {
		toSerialize["merrMsg"] = o.MerrMsg
	}
	return json.Marshal(toSerialize)
}

type NullableAccountResponse struct {
	value *AccountResponse
	isSet bool
}

func (v NullableAccountResponse) Get() *AccountResponse {
	return v.value
}

func (v *NullableAccountResponse) Set(val *AccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResponse(val *AccountResponse) *NullableAccountResponse {
	return &NullableAccountResponse{value: val, isSet: true}
}

func (v NullableAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


