/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoGetRequestParamsAllOf struct for CardInfoGetRequestParamsAllOf
type CardInfoGetRequestParamsAllOf struct {
	PayNowIdParam *CardInfoGetRequestParamsAllOfPayNowIdParam `json:"payNowIdParam,omitempty"`
}

// NewCardInfoGetRequestParamsAllOf instantiates a new CardInfoGetRequestParamsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoGetRequestParamsAllOf() *CardInfoGetRequestParamsAllOf {
	this := CardInfoGetRequestParamsAllOf{}
	return &this
}

// NewCardInfoGetRequestParamsAllOfWithDefaults instantiates a new CardInfoGetRequestParamsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoGetRequestParamsAllOfWithDefaults() *CardInfoGetRequestParamsAllOf {
	this := CardInfoGetRequestParamsAllOf{}
	return &this
}

// GetPayNowIdParam returns the PayNowIdParam field value if set, zero value otherwise.
func (o *CardInfoGetRequestParamsAllOf) GetPayNowIdParam() CardInfoGetRequestParamsAllOfPayNowIdParam {
	if o == nil || o.PayNowIdParam == nil {
		var ret CardInfoGetRequestParamsAllOfPayNowIdParam
		return ret
	}
	return *o.PayNowIdParam
}

// GetPayNowIdParamOk returns a tuple with the PayNowIdParam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardInfoGetRequestParamsAllOf) GetPayNowIdParamOk() (*CardInfoGetRequestParamsAllOfPayNowIdParam, bool) {
	if o == nil || o.PayNowIdParam == nil {
		return nil, false
	}
	return o.PayNowIdParam, true
}

// HasPayNowIdParam returns a boolean if a field has been set.
func (o *CardInfoGetRequestParamsAllOf) HasPayNowIdParam() bool {
	if o != nil && o.PayNowIdParam != nil {
		return true
	}

	return false
}

// SetPayNowIdParam gets a reference to the given CardInfoGetRequestParamsAllOfPayNowIdParam and assigns it to the PayNowIdParam field.
func (o *CardInfoGetRequestParamsAllOf) SetPayNowIdParam(v CardInfoGetRequestParamsAllOfPayNowIdParam) {
	o.PayNowIdParam = &v
}

func (o CardInfoGetRequestParamsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PayNowIdParam != nil {
		toSerialize["payNowIdParam"] = o.PayNowIdParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoGetRequestParamsAllOf struct {
	value *CardInfoGetRequestParamsAllOf
	isSet bool
}

func (v NullableCardInfoGetRequestParamsAllOf) Get() *CardInfoGetRequestParamsAllOf {
	return v.value
}

func (v *NullableCardInfoGetRequestParamsAllOf) Set(val *CardInfoGetRequestParamsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoGetRequestParamsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoGetRequestParamsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoGetRequestParamsAllOf(val *CardInfoGetRequestParamsAllOf) *NullableCardInfoGetRequestParamsAllOf {
	return &NullableCardInfoGetRequestParamsAllOf{value: val, isSet: true}
}

func (v NullableCardInfoGetRequestParamsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoGetRequestParamsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


