/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardAuthorizeRequestParamsAllOf struct for CardAuthorizeRequestParamsAllOf
type CardAuthorizeRequestParamsAllOf struct {
	PayNowIdParam *CardAuthorizeRequestParamsAllOfPayNowIdParam `json:"payNowIdParam,omitempty"`
}

// NewCardAuthorizeRequestParamsAllOf instantiates a new CardAuthorizeRequestParamsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardAuthorizeRequestParamsAllOf() *CardAuthorizeRequestParamsAllOf {
	this := CardAuthorizeRequestParamsAllOf{}
	return &this
}

// NewCardAuthorizeRequestParamsAllOfWithDefaults instantiates a new CardAuthorizeRequestParamsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardAuthorizeRequestParamsAllOfWithDefaults() *CardAuthorizeRequestParamsAllOf {
	this := CardAuthorizeRequestParamsAllOf{}
	return &this
}

// GetPayNowIdParam returns the PayNowIdParam field value if set, zero value otherwise.
func (o *CardAuthorizeRequestParamsAllOf) GetPayNowIdParam() CardAuthorizeRequestParamsAllOfPayNowIdParam {
	if o == nil || o.PayNowIdParam == nil {
		var ret CardAuthorizeRequestParamsAllOfPayNowIdParam
		return ret
	}
	return *o.PayNowIdParam
}

// GetPayNowIdParamOk returns a tuple with the PayNowIdParam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAuthorizeRequestParamsAllOf) GetPayNowIdParamOk() (*CardAuthorizeRequestParamsAllOfPayNowIdParam, bool) {
	if o == nil || o.PayNowIdParam == nil {
		return nil, false
	}
	return o.PayNowIdParam, true
}

// HasPayNowIdParam returns a boolean if a field has been set.
func (o *CardAuthorizeRequestParamsAllOf) HasPayNowIdParam() bool {
	if o != nil && o.PayNowIdParam != nil {
		return true
	}

	return false
}

// SetPayNowIdParam gets a reference to the given CardAuthorizeRequestParamsAllOfPayNowIdParam and assigns it to the PayNowIdParam field.
func (o *CardAuthorizeRequestParamsAllOf) SetPayNowIdParam(v CardAuthorizeRequestParamsAllOfPayNowIdParam) {
	o.PayNowIdParam = &v
}

func (o CardAuthorizeRequestParamsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PayNowIdParam != nil {
		toSerialize["payNowIdParam"] = o.PayNowIdParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardAuthorizeRequestParamsAllOf struct {
	value *CardAuthorizeRequestParamsAllOf
	isSet bool
}

func (v NullableCardAuthorizeRequestParamsAllOf) Get() *CardAuthorizeRequestParamsAllOf {
	return v.value
}

func (v *NullableCardAuthorizeRequestParamsAllOf) Set(val *CardAuthorizeRequestParamsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCardAuthorizeRequestParamsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCardAuthorizeRequestParamsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardAuthorizeRequestParamsAllOf(val *CardAuthorizeRequestParamsAllOf) *NullableCardAuthorizeRequestParamsAllOf {
	return &NullableCardAuthorizeRequestParamsAllOf{value: val, isSet: true}
}

func (v NullableCardAuthorizeRequestParamsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardAuthorizeRequestParamsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


