/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardCaptureRequestAllOf struct for CardCaptureRequestAllOf
type CardCaptureRequestAllOf struct {
	OrderId *string `json:"orderId,omitempty"`
	Amount *string `json:"amount,omitempty"`
}

// NewCardCaptureRequestAllOf instantiates a new CardCaptureRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardCaptureRequestAllOf() *CardCaptureRequestAllOf {
	this := CardCaptureRequestAllOf{}
	return &this
}

// NewCardCaptureRequestAllOfWithDefaults instantiates a new CardCaptureRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardCaptureRequestAllOfWithDefaults() *CardCaptureRequestAllOf {
	this := CardCaptureRequestAllOf{}
	return &this
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *CardCaptureRequestAllOf) GetOrderId() string {
	if o == nil || o.OrderId == nil {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestAllOf) GetOrderIdOk() (*string, bool) {
	if o == nil || o.OrderId == nil {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *CardCaptureRequestAllOf) HasOrderId() bool {
	if o != nil && o.OrderId != nil {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *CardCaptureRequestAllOf) SetOrderId(v string) {
	o.OrderId = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CardCaptureRequestAllOf) GetAmount() string {
	if o == nil || o.Amount == nil {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestAllOf) GetAmountOk() (*string, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CardCaptureRequestAllOf) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *CardCaptureRequestAllOf) SetAmount(v string) {
	o.Amount = &v
}

func (o CardCaptureRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OrderId != nil {
		toSerialize["orderId"] = o.OrderId
	}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableCardCaptureRequestAllOf struct {
	value *CardCaptureRequestAllOf
	isSet bool
}

func (v NullableCardCaptureRequestAllOf) Get() *CardCaptureRequestAllOf {
	return v.value
}

func (v *NullableCardCaptureRequestAllOf) Set(val *CardCaptureRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCardCaptureRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCardCaptureRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardCaptureRequestAllOf(val *CardCaptureRequestAllOf) *NullableCardCaptureRequestAllOf {
	return &NullableCardCaptureRequestAllOf{value: val, isSet: true}
}

func (v NullableCardCaptureRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardCaptureRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


