/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoUpdateRequest struct for CardInfoUpdateRequest
type CardInfoUpdateRequest struct {
	Params CardInfoUpdateRequestParams `json:"params"`
	AuthHash string `json:"authHash"`
}

// NewCardInfoUpdateRequest instantiates a new CardInfoUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoUpdateRequest(params CardInfoUpdateRequestParams, authHash string) *CardInfoUpdateRequest {
	this := CardInfoUpdateRequest{}
	this.Params = params
	this.AuthHash = authHash
	return &this
}

// NewCardInfoUpdateRequestWithDefaults instantiates a new CardInfoUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoUpdateRequestWithDefaults() *CardInfoUpdateRequest {
	this := CardInfoUpdateRequest{}
	return &this
}

// GetParams returns the Params field value
func (o *CardInfoUpdateRequest) GetParams() CardInfoUpdateRequestParams {
	if o == nil {
		var ret CardInfoUpdateRequestParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequest) GetParamsOk() (*CardInfoUpdateRequestParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *CardInfoUpdateRequest) SetParams(v CardInfoUpdateRequestParams) {
	o.Params = v
}

// GetAuthHash returns the AuthHash field value
func (o *CardInfoUpdateRequest) GetAuthHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthHash
}

// GetAuthHashOk returns a tuple with the AuthHash field value
// and a boolean to check if the value has been set.
func (o *CardInfoUpdateRequest) GetAuthHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthHash, true
}

// SetAuthHash sets field value
func (o *CardInfoUpdateRequest) SetAuthHash(v string) {
	o.AuthHash = v
}

func (o CardInfoUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["params"] = o.Params
	}
	if true {
		toSerialize["authHash"] = o.AuthHash
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoUpdateRequest struct {
	value *CardInfoUpdateRequest
	isSet bool
}

func (v NullableCardInfoUpdateRequest) Get() *CardInfoUpdateRequest {
	return v.value
}

func (v *NullableCardInfoUpdateRequest) Set(val *CardInfoUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoUpdateRequest(val *CardInfoUpdateRequest) *NullableCardInfoUpdateRequest {
	return &NullableCardInfoUpdateRequest{value: val, isSet: true}
}

func (v NullableCardInfoUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


