/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardCaptureRequestParam struct for CardCaptureRequestParam
type CardCaptureRequestParam struct {
	OrderId string `json:"orderId"`
	Amount string `json:"amount"`
}

// NewCardCaptureRequestParam instantiates a new CardCaptureRequestParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardCaptureRequestParam(orderId string, amount string) *CardCaptureRequestParam {
	this := CardCaptureRequestParam{}
	this.OrderId = orderId
	this.Amount = amount
	return &this
}

// NewCardCaptureRequestParamWithDefaults instantiates a new CardCaptureRequestParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardCaptureRequestParamWithDefaults() *CardCaptureRequestParam {
	this := CardCaptureRequestParam{}
	return &this
}

// GetOrderId returns the OrderId field value
func (o *CardCaptureRequestParam) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestParam) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *CardCaptureRequestParam) SetOrderId(v string) {
	o.OrderId = v
}

// GetAmount returns the Amount field value
func (o *CardCaptureRequestParam) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CardCaptureRequestParam) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CardCaptureRequestParam) SetAmount(v string) {
	o.Amount = v
}

func (o CardCaptureRequestParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["orderId"] = o.OrderId
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableCardCaptureRequestParam struct {
	value *CardCaptureRequestParam
	isSet bool
}

func (v NullableCardCaptureRequestParam) Get() *CardCaptureRequestParam {
	return v.value
}

func (v *NullableCardCaptureRequestParam) Set(val *CardCaptureRequestParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardCaptureRequestParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardCaptureRequestParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardCaptureRequestParam(val *CardCaptureRequestParam) *NullableCardCaptureRequestParam {
	return &NullableCardCaptureRequestParam{value: val, isSet: true}
}

func (v NullableCardCaptureRequestParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardCaptureRequestParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


