/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoAddRequestParamsAllOfPayNowIdParam struct for CardInfoAddRequestParamsAllOfPayNowIdParam
type CardInfoAddRequestParamsAllOfPayNowIdParam struct {
	AccountParam CardInfoAddRequestParamsAllOfPayNowIdParamAccountParam `json:"accountParam"`
}

// NewCardInfoAddRequestParamsAllOfPayNowIdParam instantiates a new CardInfoAddRequestParamsAllOfPayNowIdParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoAddRequestParamsAllOfPayNowIdParam(accountParam CardInfoAddRequestParamsAllOfPayNowIdParamAccountParam) *CardInfoAddRequestParamsAllOfPayNowIdParam {
	this := CardInfoAddRequestParamsAllOfPayNowIdParam{}
	this.AccountParam = accountParam
	return &this
}

// NewCardInfoAddRequestParamsAllOfPayNowIdParamWithDefaults instantiates a new CardInfoAddRequestParamsAllOfPayNowIdParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoAddRequestParamsAllOfPayNowIdParamWithDefaults() *CardInfoAddRequestParamsAllOfPayNowIdParam {
	this := CardInfoAddRequestParamsAllOfPayNowIdParam{}
	return &this
}

// GetAccountParam returns the AccountParam field value
func (o *CardInfoAddRequestParamsAllOfPayNowIdParam) GetAccountParam() CardInfoAddRequestParamsAllOfPayNowIdParamAccountParam {
	if o == nil {
		var ret CardInfoAddRequestParamsAllOfPayNowIdParamAccountParam
		return ret
	}

	return o.AccountParam
}

// GetAccountParamOk returns a tuple with the AccountParam field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequestParamsAllOfPayNowIdParam) GetAccountParamOk() (*CardInfoAddRequestParamsAllOfPayNowIdParamAccountParam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountParam, true
}

// SetAccountParam sets field value
func (o *CardInfoAddRequestParamsAllOfPayNowIdParam) SetAccountParam(v CardInfoAddRequestParamsAllOfPayNowIdParamAccountParam) {
	o.AccountParam = v
}

func (o CardInfoAddRequestParamsAllOfPayNowIdParam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountParam"] = o.AccountParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoAddRequestParamsAllOfPayNowIdParam struct {
	value *CardInfoAddRequestParamsAllOfPayNowIdParam
	isSet bool
}

func (v NullableCardInfoAddRequestParamsAllOfPayNowIdParam) Get() *CardInfoAddRequestParamsAllOfPayNowIdParam {
	return v.value
}

func (v *NullableCardInfoAddRequestParamsAllOfPayNowIdParam) Set(val *CardInfoAddRequestParamsAllOfPayNowIdParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoAddRequestParamsAllOfPayNowIdParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoAddRequestParamsAllOfPayNowIdParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoAddRequestParamsAllOfPayNowIdParam(val *CardInfoAddRequestParamsAllOfPayNowIdParam) *NullableCardInfoAddRequestParamsAllOfPayNowIdParam {
	return &NullableCardInfoAddRequestParamsAllOfPayNowIdParam{value: val, isSet: true}
}

func (v NullableCardInfoAddRequestParamsAllOfPayNowIdParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoAddRequestParamsAllOfPayNowIdParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


