/*
Veritrance API

Veritrance API Requestの形式はcomponentsを参照。文字列にしたものを各Requestのparamsに用いる 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veritrance_paynow

import (
	"encoding/json"
)

// CardInfoAddRequestParams struct for CardInfoAddRequestParams
type CardInfoAddRequestParams struct {
	TxnVersion string `json:"txnVersion"`
	DummyRequest string `json:"dummyRequest"`
	MerchantCcid string `json:"merchantCcid"`
	PayNowIdParam CardInfoAddRequestParamsAllOfPayNowIdParam `json:"payNowIdParam"`
}

// NewCardInfoAddRequestParams instantiates a new CardInfoAddRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardInfoAddRequestParams(txnVersion string, dummyRequest string, merchantCcid string, payNowIdParam CardInfoAddRequestParamsAllOfPayNowIdParam) *CardInfoAddRequestParams {
	this := CardInfoAddRequestParams{}
	this.TxnVersion = txnVersion
	this.DummyRequest = dummyRequest
	this.MerchantCcid = merchantCcid
	this.PayNowIdParam = payNowIdParam
	return &this
}

// NewCardInfoAddRequestParamsWithDefaults instantiates a new CardInfoAddRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardInfoAddRequestParamsWithDefaults() *CardInfoAddRequestParams {
	this := CardInfoAddRequestParams{}
	return &this
}

// GetTxnVersion returns the TxnVersion field value
func (o *CardInfoAddRequestParams) GetTxnVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxnVersion
}

// GetTxnVersionOk returns a tuple with the TxnVersion field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequestParams) GetTxnVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxnVersion, true
}

// SetTxnVersion sets field value
func (o *CardInfoAddRequestParams) SetTxnVersion(v string) {
	o.TxnVersion = v
}

// GetDummyRequest returns the DummyRequest field value
func (o *CardInfoAddRequestParams) GetDummyRequest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DummyRequest
}

// GetDummyRequestOk returns a tuple with the DummyRequest field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequestParams) GetDummyRequestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DummyRequest, true
}

// SetDummyRequest sets field value
func (o *CardInfoAddRequestParams) SetDummyRequest(v string) {
	o.DummyRequest = v
}

// GetMerchantCcid returns the MerchantCcid field value
func (o *CardInfoAddRequestParams) GetMerchantCcid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantCcid
}

// GetMerchantCcidOk returns a tuple with the MerchantCcid field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequestParams) GetMerchantCcidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantCcid, true
}

// SetMerchantCcid sets field value
func (o *CardInfoAddRequestParams) SetMerchantCcid(v string) {
	o.MerchantCcid = v
}

// GetPayNowIdParam returns the PayNowIdParam field value
func (o *CardInfoAddRequestParams) GetPayNowIdParam() CardInfoAddRequestParamsAllOfPayNowIdParam {
	if o == nil {
		var ret CardInfoAddRequestParamsAllOfPayNowIdParam
		return ret
	}

	return o.PayNowIdParam
}

// GetPayNowIdParamOk returns a tuple with the PayNowIdParam field value
// and a boolean to check if the value has been set.
func (o *CardInfoAddRequestParams) GetPayNowIdParamOk() (*CardInfoAddRequestParamsAllOfPayNowIdParam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PayNowIdParam, true
}

// SetPayNowIdParam sets field value
func (o *CardInfoAddRequestParams) SetPayNowIdParam(v CardInfoAddRequestParamsAllOfPayNowIdParam) {
	o.PayNowIdParam = v
}

func (o CardInfoAddRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["txnVersion"] = o.TxnVersion
	}
	if true {
		toSerialize["dummyRequest"] = o.DummyRequest
	}
	if true {
		toSerialize["merchantCcid"] = o.MerchantCcid
	}
	if true {
		toSerialize["payNowIdParam"] = o.PayNowIdParam
	}
	return json.Marshal(toSerialize)
}

type NullableCardInfoAddRequestParams struct {
	value *CardInfoAddRequestParams
	isSet bool
}

func (v NullableCardInfoAddRequestParams) Get() *CardInfoAddRequestParams {
	return v.value
}

func (v *NullableCardInfoAddRequestParams) Set(val *CardInfoAddRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableCardInfoAddRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableCardInfoAddRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardInfoAddRequestParams(val *CardInfoAddRequestParams) *NullableCardInfoAddRequestParams {
	return &NullableCardInfoAddRequestParams{value: val, isSet: true}
}

func (v NullableCardInfoAddRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardInfoAddRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


